
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file CongThucTinhQuyDoi.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using PMS.Entities.Validation;
#endregion

namespace PMS.Entities
{
	///<summary>
	/// An object representation of the 'CongThucTinhQuyDoi' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class CongThucTinhQuyDoiBase : EntityBase, ICongThucTinhQuyDoi, IEntityId<CongThucTinhQuyDoiKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private CongThucTinhQuyDoiEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private CongThucTinhQuyDoiEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private CongThucTinhQuyDoiEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<CongThucTinhQuyDoi> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CongThucTinhQuyDoiEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CongThucTinhQuyDoiEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="CongThucTinhQuyDoiBase"/> instance.
		///</summary>
		public CongThucTinhQuyDoiBase()
		{
			this.entityData = new CongThucTinhQuyDoiEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="CongThucTinhQuyDoiBase"/> instance.
		///</summary>
		///<param name="_maLoaiCongThuc"></param>
		///<param name="_namHoc"></param>
		///<param name="_hocKy"></param>
		///<param name="_congThuc"></param>
		///<param name="_toanHangSuDung"></param>
		///<param name="_apDung"></param>
		///<param name="_dienGiai"></param>
		///<param name="_tinhVuotDinhMuc"></param>
		///<param name="_tinhVuotTran"></param>
		public CongThucTinhQuyDoiBase(System.String _maLoaiCongThuc, System.String _namHoc, 
			System.String _hocKy, System.String _congThuc, System.String _toanHangSuDung, 
			System.Boolean? _apDung, System.String _dienGiai, System.Boolean? _tinhVuotDinhMuc, 
			System.Boolean? _tinhVuotTran)
		{
			this.entityData = new CongThucTinhQuyDoiEntityData();
			this.backupData = null;

			this.MaLoaiCongThuc = _maLoaiCongThuc;
			this.NamHoc = _namHoc;
			this.HocKy = _hocKy;
			this.CongThuc = _congThuc;
			this.ToanHangSuDung = _toanHangSuDung;
			this.ApDung = _apDung;
			this.DienGiai = _dienGiai;
			this.TinhVuotDinhMuc = _tinhVuotDinhMuc;
			this.TinhVuotTran = _tinhVuotTran;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="CongThucTinhQuyDoi"/> instance.
		///</summary>
		///<param name="_maLoaiCongThuc"></param>
		///<param name="_namHoc"></param>
		///<param name="_hocKy"></param>
		///<param name="_congThuc"></param>
		///<param name="_toanHangSuDung"></param>
		///<param name="_apDung"></param>
		///<param name="_dienGiai"></param>
		///<param name="_tinhVuotDinhMuc"></param>
		///<param name="_tinhVuotTran"></param>
		public static CongThucTinhQuyDoi CreateCongThucTinhQuyDoi(System.String _maLoaiCongThuc, System.String _namHoc, 
			System.String _hocKy, System.String _congThuc, System.String _toanHangSuDung, 
			System.Boolean? _apDung, System.String _dienGiai, System.Boolean? _tinhVuotDinhMuc, 
			System.Boolean? _tinhVuotTran)
		{
			CongThucTinhQuyDoi newCongThucTinhQuyDoi = new CongThucTinhQuyDoi();
			newCongThucTinhQuyDoi.MaLoaiCongThuc = _maLoaiCongThuc;
			newCongThucTinhQuyDoi.NamHoc = _namHoc;
			newCongThucTinhQuyDoi.HocKy = _hocKy;
			newCongThucTinhQuyDoi.CongThuc = _congThuc;
			newCongThucTinhQuyDoi.ToanHangSuDung = _toanHangSuDung;
			newCongThucTinhQuyDoi.ApDung = _apDung;
			newCongThucTinhQuyDoi.DienGiai = _dienGiai;
			newCongThucTinhQuyDoi.TinhVuotDinhMuc = _tinhVuotDinhMuc;
			newCongThucTinhQuyDoi.TinhVuotTran = _tinhVuotTran;
			return newCongThucTinhQuyDoi;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MaCongThuc property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "MaCongThuc is required")]




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 MaCongThuc
		{
			get
			{
				return this.entityData.MaCongThuc; 
			}
			
			set
			{
				if (this.entityData.MaCongThuc == value)
					return;
				
                OnPropertyChanging("MaCongThuc");                    
				OnColumnChanging(CongThucTinhQuyDoiColumn.MaCongThuc, this.entityData.MaCongThuc);
				this.entityData.MaCongThuc = value;
				this.EntityId.MaCongThuc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhQuyDoiColumn.MaCongThuc, this.entityData.MaCongThuc);
				OnPropertyChanged("MaCongThuc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaLoaiCongThuc property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String MaLoaiCongThuc
		{
			get
			{
				return this.entityData.MaLoaiCongThuc; 
			}
			
			set
			{
				if (this.entityData.MaLoaiCongThuc == value)
					return;
				
                OnPropertyChanging("MaLoaiCongThuc");                    
				OnColumnChanging(CongThucTinhQuyDoiColumn.MaLoaiCongThuc, this.entityData.MaLoaiCongThuc);
				this.entityData.MaLoaiCongThuc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhQuyDoiColumn.MaLoaiCongThuc, this.entityData.MaLoaiCongThuc);
				OnPropertyChanged("MaLoaiCongThuc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NamHoc property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String NamHoc
		{
			get
			{
				return this.entityData.NamHoc; 
			}
			
			set
			{
				if (this.entityData.NamHoc == value)
					return;
				
                OnPropertyChanging("NamHoc");                    
				OnColumnChanging(CongThucTinhQuyDoiColumn.NamHoc, this.entityData.NamHoc);
				this.entityData.NamHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhQuyDoiColumn.NamHoc, this.entityData.NamHoc);
				OnPropertyChanged("NamHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the HocKy property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String HocKy
		{
			get
			{
				return this.entityData.HocKy; 
			}
			
			set
			{
				if (this.entityData.HocKy == value)
					return;
				
                OnPropertyChanging("HocKy");                    
				OnColumnChanging(CongThucTinhQuyDoiColumn.HocKy, this.entityData.HocKy);
				this.entityData.HocKy = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhQuyDoiColumn.HocKy, this.entityData.HocKy);
				OnPropertyChanged("HocKy");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CongThuc property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		[Required(ErrorMessage = "CongThuc is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.String CongThuc
		{
			get
			{
				return this.entityData.CongThuc; 
			}
			
			set
			{
				if (this.entityData.CongThuc == value)
					return;
				
                OnPropertyChanging("CongThuc");                    
				OnColumnChanging(CongThucTinhQuyDoiColumn.CongThuc, this.entityData.CongThuc);
				this.entityData.CongThuc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhQuyDoiColumn.CongThuc, this.entityData.CongThuc);
				OnPropertyChanged("CongThuc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ToanHangSuDung property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		[Required(ErrorMessage = "ToanHangSuDung is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.String ToanHangSuDung
		{
			get
			{
				return this.entityData.ToanHangSuDung; 
			}
			
			set
			{
				if (this.entityData.ToanHangSuDung == value)
					return;
				
                OnPropertyChanging("ToanHangSuDung");                    
				OnColumnChanging(CongThucTinhQuyDoiColumn.ToanHangSuDung, this.entityData.ToanHangSuDung);
				this.entityData.ToanHangSuDung = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhQuyDoiColumn.ToanHangSuDung, this.entityData.ToanHangSuDung);
				OnPropertyChanged("ToanHangSuDung");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ApDung property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? ApDung
		{
			get
			{
				return this.entityData.ApDung; 
			}
			
			set
			{
				if (this.entityData.ApDung == value)
					return;
				
                OnPropertyChanging("ApDung");                    
				OnColumnChanging(CongThucTinhQuyDoiColumn.ApDung, this.entityData.ApDung);
				this.entityData.ApDung = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhQuyDoiColumn.ApDung, this.entityData.ApDung);
				OnPropertyChanged("ApDung");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DienGiai property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String DienGiai
		{
			get
			{
				return this.entityData.DienGiai; 
			}
			
			set
			{
				if (this.entityData.DienGiai == value)
					return;
				
                OnPropertyChanging("DienGiai");                    
				OnColumnChanging(CongThucTinhQuyDoiColumn.DienGiai, this.entityData.DienGiai);
				this.entityData.DienGiai = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhQuyDoiColumn.DienGiai, this.entityData.DienGiai);
				OnPropertyChanged("DienGiai");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TinhVuotDinhMuc property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? TinhVuotDinhMuc
		{
			get
			{
				return this.entityData.TinhVuotDinhMuc; 
			}
			
			set
			{
				if (this.entityData.TinhVuotDinhMuc == value)
					return;
				
                OnPropertyChanging("TinhVuotDinhMuc");                    
				OnColumnChanging(CongThucTinhQuyDoiColumn.TinhVuotDinhMuc, this.entityData.TinhVuotDinhMuc);
				this.entityData.TinhVuotDinhMuc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhQuyDoiColumn.TinhVuotDinhMuc, this.entityData.TinhVuotDinhMuc);
				OnPropertyChanged("TinhVuotDinhMuc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TinhVuotTran property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? TinhVuotTran
		{
			get
			{
				return this.entityData.TinhVuotTran; 
			}
			
			set
			{
				if (this.entityData.TinhVuotTran == value)
					return;
				
                OnPropertyChanging("TinhVuotTran");                    
				OnColumnChanging(CongThucTinhQuyDoiColumn.TinhVuotTran, this.entityData.TinhVuotTran);
				this.entityData.TinhVuotTran = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhQuyDoiColumn.TinhVuotTran, this.entityData.TinhVuotTran);
				OnPropertyChanged("TinhVuotTran");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="LoaiCongThuc"/>.
		/// </summary>
		/// <value>The source LoaiCongThuc for MaLoaiCongThuc.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual LoaiCongThuc MaLoaiCongThucSource
      	{
            get { return entityData.MaLoaiCongThucSource; }
            set { entityData.MaLoaiCongThucSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("MaLoaiCongThuc", "Ma Loai Cong Thuc", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("NamHoc", "Nam Hoc", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("HocKy", "Hoc Ky", 20));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("CongThuc", "Cong Thuc"));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("ToanHangSuDung", "Toan Hang Su Dung"));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "CongThucTinhQuyDoi"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MaCongThuc", "MaLoaiCongThuc", "NamHoc", "HocKy", "CongThuc", "ToanHangSuDung", "ApDung", "DienGiai", "TinhVuotDinhMuc", "TinhVuotTran"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as CongThucTinhQuyDoiEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (CongThucTinhQuyDoi) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<CongThucTinhQuyDoi>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as CongThucTinhQuyDoi);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed CongThucTinhQuyDoi Entity 
		///</summary>
		protected virtual CongThucTinhQuyDoi Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			CongThucTinhQuyDoi copy = new CongThucTinhQuyDoi();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.MaCongThuc = this.MaCongThuc;
				copy.MaLoaiCongThuc = this.MaLoaiCongThuc;
				copy.NamHoc = this.NamHoc;
				copy.HocKy = this.HocKy;
				copy.CongThuc = this.CongThuc;
				copy.ToanHangSuDung = this.ToanHangSuDung;
				copy.ApDung = this.ApDung;
				copy.DienGiai = this.DienGiai;
				copy.TinhVuotDinhMuc = this.TinhVuotDinhMuc;
				copy.TinhVuotTran = this.TinhVuotTran;
			
			if (this.MaLoaiCongThucSource != null && existingCopies.Contains(this.MaLoaiCongThucSource))
				copy.MaLoaiCongThucSource = existingCopies[this.MaLoaiCongThucSource] as LoaiCongThuc;
			else
				copy.MaLoaiCongThucSource = MakeCopyOf(this.MaLoaiCongThucSource, existingCopies) as LoaiCongThuc;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed CongThucTinhQuyDoi Entity 
		///</summary>
		public virtual CongThucTinhQuyDoi Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed CongThucTinhQuyDoi Entity which is a deep copy of the current entity.
		///</summary>
		public virtual CongThucTinhQuyDoi DeepCopy()
		{
			return EntityHelper.Clone<CongThucTinhQuyDoi>(this as CongThucTinhQuyDoi);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as CongThucTinhQuyDoiEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new CongThucTinhQuyDoiEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as CongThucTinhQuyDoiEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(CongThucTinhQuyDoiColumn column)
		{
			switch(column)
			{
					case CongThucTinhQuyDoiColumn.MaCongThuc:
					return entityData.MaCongThuc != _originalData.MaCongThuc;
					case CongThucTinhQuyDoiColumn.MaLoaiCongThuc:
					return entityData.MaLoaiCongThuc != _originalData.MaLoaiCongThuc;
					case CongThucTinhQuyDoiColumn.NamHoc:
					return entityData.NamHoc != _originalData.NamHoc;
					case CongThucTinhQuyDoiColumn.HocKy:
					return entityData.HocKy != _originalData.HocKy;
					case CongThucTinhQuyDoiColumn.CongThuc:
					return entityData.CongThuc != _originalData.CongThuc;
					case CongThucTinhQuyDoiColumn.ToanHangSuDung:
					return entityData.ToanHangSuDung != _originalData.ToanHangSuDung;
					case CongThucTinhQuyDoiColumn.ApDung:
					return entityData.ApDung != _originalData.ApDung;
					case CongThucTinhQuyDoiColumn.DienGiai:
					return entityData.DienGiai != _originalData.DienGiai;
					case CongThucTinhQuyDoiColumn.TinhVuotDinhMuc:
					return entityData.TinhVuotDinhMuc != _originalData.TinhVuotDinhMuc;
					case CongThucTinhQuyDoiColumn.TinhVuotTran:
					return entityData.TinhVuotTran != _originalData.TinhVuotTran;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< CongThucTinhQuyDoiColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MaCongThuc != _originalData.MaCongThuc;
			result = result || entityData.MaLoaiCongThuc != _originalData.MaLoaiCongThuc;
			result = result || entityData.NamHoc != _originalData.NamHoc;
			result = result || entityData.HocKy != _originalData.HocKy;
			result = result || entityData.CongThuc != _originalData.CongThuc;
			result = result || entityData.ToanHangSuDung != _originalData.ToanHangSuDung;
			result = result || entityData.ApDung != _originalData.ApDung;
			result = result || entityData.DienGiai != _originalData.DienGiai;
			result = result || entityData.TinhVuotDinhMuc != _originalData.TinhVuotDinhMuc;
			result = result || entityData.TinhVuotTran != _originalData.TinhVuotTran;
			return result;
		}	
		
		///<summary>
		///  Returns a CongThucTinhQuyDoi Entity with the original data.
		///</summary>
		public CongThucTinhQuyDoi GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateCongThucTinhQuyDoi(
				_originalData.MaLoaiCongThuc,
				_originalData.NamHoc,
				_originalData.HocKy,
				_originalData.CongThuc,
				_originalData.ToanHangSuDung,
				_originalData.ApDung,
				_originalData.DienGiai,
				_originalData.TinhVuotDinhMuc,
				_originalData.TinhVuotTran
				);
				
			return (CongThucTinhQuyDoi)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="CongThucTinhQuyDoiBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is CongThucTinhQuyDoiBase)
				return ValueEquals(this, (CongThucTinhQuyDoiBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="CongThucTinhQuyDoiBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MaCongThuc.GetHashCode() ^ 
					((this.MaLoaiCongThuc == null) ? string.Empty : this.MaLoaiCongThuc.ToString()).GetHashCode() ^ 
					((this.NamHoc == null) ? string.Empty : this.NamHoc.ToString()).GetHashCode() ^ 
					((this.HocKy == null) ? string.Empty : this.HocKy.ToString()).GetHashCode() ^ 
					this.CongThuc.GetHashCode() ^ 
					this.ToanHangSuDung.GetHashCode() ^ 
					((this.ApDung == null) ? string.Empty : this.ApDung.ToString()).GetHashCode() ^ 
					((this.DienGiai == null) ? string.Empty : this.DienGiai.ToString()).GetHashCode() ^ 
					((this.TinhVuotDinhMuc == null) ? string.Empty : this.TinhVuotDinhMuc.ToString()).GetHashCode() ^ 
					((this.TinhVuotTran == null) ? string.Empty : this.TinhVuotTran.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="CongThucTinhQuyDoiBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(CongThucTinhQuyDoiBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="CongThucTinhQuyDoiBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="CongThucTinhQuyDoiBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="CongThucTinhQuyDoiBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(CongThucTinhQuyDoiBase Object1, CongThucTinhQuyDoiBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MaCongThuc != Object2.MaCongThuc)
				equal = false;
			if ( Object1.MaLoaiCongThuc != null && Object2.MaLoaiCongThuc != null )
			{
				if (Object1.MaLoaiCongThuc != Object2.MaLoaiCongThuc)
					equal = false;
			}
			else if (Object1.MaLoaiCongThuc == null ^ Object2.MaLoaiCongThuc == null )
			{
				equal = false;
			}
			if ( Object1.NamHoc != null && Object2.NamHoc != null )
			{
				if (Object1.NamHoc != Object2.NamHoc)
					equal = false;
			}
			else if (Object1.NamHoc == null ^ Object2.NamHoc == null )
			{
				equal = false;
			}
			if ( Object1.HocKy != null && Object2.HocKy != null )
			{
				if (Object1.HocKy != Object2.HocKy)
					equal = false;
			}
			else if (Object1.HocKy == null ^ Object2.HocKy == null )
			{
				equal = false;
			}
			if (Object1.CongThuc != Object2.CongThuc)
				equal = false;
			if (Object1.ToanHangSuDung != Object2.ToanHangSuDung)
				equal = false;
			if ( Object1.ApDung != null && Object2.ApDung != null )
			{
				if (Object1.ApDung != Object2.ApDung)
					equal = false;
			}
			else if (Object1.ApDung == null ^ Object2.ApDung == null )
			{
				equal = false;
			}
			if ( Object1.DienGiai != null && Object2.DienGiai != null )
			{
				if (Object1.DienGiai != Object2.DienGiai)
					equal = false;
			}
			else if (Object1.DienGiai == null ^ Object2.DienGiai == null )
			{
				equal = false;
			}
			if ( Object1.TinhVuotDinhMuc != null && Object2.TinhVuotDinhMuc != null )
			{
				if (Object1.TinhVuotDinhMuc != Object2.TinhVuotDinhMuc)
					equal = false;
			}
			else if (Object1.TinhVuotDinhMuc == null ^ Object2.TinhVuotDinhMuc == null )
			{
				equal = false;
			}
			if ( Object1.TinhVuotTran != null && Object2.TinhVuotTran != null )
			{
				if (Object1.TinhVuotTran != Object2.TinhVuotTran)
					equal = false;
			}
			else if (Object1.TinhVuotTran == null ^ Object2.TinhVuotTran == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((CongThucTinhQuyDoiBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static CongThucTinhQuyDoiComparer GetComparer()
        {
            return new CongThucTinhQuyDoiComparer();
        }
        */

        // Comparer delegates back to CongThucTinhQuyDoi
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(CongThucTinhQuyDoi rhs, CongThucTinhQuyDoiColumn which)
        {
            switch (which)
            {
            	
            	
            	case CongThucTinhQuyDoiColumn.MaCongThuc:
            		return this.MaCongThuc.CompareTo(rhs.MaCongThuc);
            		
            		                 
            	
            	
            	case CongThucTinhQuyDoiColumn.MaLoaiCongThuc:
            		return this.MaLoaiCongThuc.CompareTo(rhs.MaLoaiCongThuc);
            		
            		                 
            	
            	
            	case CongThucTinhQuyDoiColumn.NamHoc:
            		return this.NamHoc.CompareTo(rhs.NamHoc);
            		
            		                 
            	
            	
            	case CongThucTinhQuyDoiColumn.HocKy:
            		return this.HocKy.CompareTo(rhs.HocKy);
            		
            		                 
            	
            	
            	case CongThucTinhQuyDoiColumn.CongThuc:
            		return this.CongThuc.CompareTo(rhs.CongThuc);
            		
            		                 
            	
            	
            	case CongThucTinhQuyDoiColumn.ToanHangSuDung:
            		return this.ToanHangSuDung.CompareTo(rhs.ToanHangSuDung);
            		
            		                 
            	
            	
            	case CongThucTinhQuyDoiColumn.ApDung:
            		return this.ApDung.Value.CompareTo(rhs.ApDung.Value);
            		
            		                 
            	
            	
            	case CongThucTinhQuyDoiColumn.DienGiai:
            		return this.DienGiai.CompareTo(rhs.DienGiai);
            		
            		                 
            	
            	
            	case CongThucTinhQuyDoiColumn.TinhVuotDinhMuc:
            		return this.TinhVuotDinhMuc.Value.CompareTo(rhs.TinhVuotDinhMuc.Value);
            		
            		                 
            	
            	
            	case CongThucTinhQuyDoiColumn.TinhVuotTran:
            		return this.TinhVuotTran.Value.CompareTo(rhs.TinhVuotTran.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<CongThucTinhQuyDoiKey> Members
		
		// member variable for the EntityId property
		private CongThucTinhQuyDoiKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual CongThucTinhQuyDoiKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new CongThucTinhQuyDoiKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) ]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("CongThucTinhQuyDoi")
					.Append("|").Append( this.MaCongThuc.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{11}{10}- MaCongThuc: {0}{10}- MaLoaiCongThuc: {1}{10}- NamHoc: {2}{10}- HocKy: {3}{10}- CongThuc: {4}{10}- ToanHangSuDung: {5}{10}- ApDung: {6}{10}- DienGiai: {7}{10}- TinhVuotDinhMuc: {8}{10}- TinhVuotTran: {9}{10}{12}", 
				this.MaCongThuc,
				(this.MaLoaiCongThuc == null) ? string.Empty : this.MaLoaiCongThuc.ToString(),
				(this.NamHoc == null) ? string.Empty : this.NamHoc.ToString(),
				(this.HocKy == null) ? string.Empty : this.HocKy.ToString(),
				this.CongThuc,
				this.ToanHangSuDung,
				(this.ApDung == null) ? string.Empty : this.ApDung.ToString(),
				(this.DienGiai == null) ? string.Empty : this.DienGiai.ToString(),
				(this.TinhVuotDinhMuc == null) ? string.Empty : this.TinhVuotDinhMuc.ToString(),
				(this.TinhVuotTran == null) ? string.Empty : this.TinhVuotTran.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'CongThucTinhQuyDoi' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class CongThucTinhQuyDoiEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// MaCongThuc : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "CongThucTinhQuyDoi"</remarks>
		public System.Int32 MaCongThuc;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// MaLoaiCongThuc : 
		/// </summary>
		public System.String MaLoaiCongThuc = null;
		
		/// <summary>
		/// NamHoc : 
		/// </summary>
		public System.String NamHoc = null;
		
		/// <summary>
		/// HocKy : 
		/// </summary>
		public System.String HocKy = null;
		
		/// <summary>
		/// CongThuc : 
		/// </summary>
		public System.String CongThuc = string.Empty;
		
		/// <summary>
		/// ToanHangSuDung : 
		/// </summary>
		public System.String ToanHangSuDung = string.Empty;
		
		/// <summary>
		/// ApDung : 
		/// </summary>
		public System.Boolean? ApDung = null;
		
		/// <summary>
		/// DienGiai : 
		/// </summary>
		public System.String DienGiai = null;
		
		/// <summary>
		/// TinhVuotDinhMuc : 
		/// </summary>
		public System.Boolean? TinhVuotDinhMuc = null;
		
		/// <summary>
		/// TinhVuotTran : 
		/// </summary>
		public System.Boolean? TinhVuotTran = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private LoaiCongThuc _maLoaiCongThucSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="LoaiCongThuc"/>.
		/// </summary>
		/// <value>The source LoaiCongThuc for MaLoaiCongThuc.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual LoaiCongThuc MaLoaiCongThucSource
      	{
            get { return this._maLoaiCongThucSource; }
            set { this._maLoaiCongThucSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			CongThucTinhQuyDoiEntityData _tmp = new CongThucTinhQuyDoiEntityData();
						
			_tmp.MaCongThuc = this.MaCongThuc;
			
			_tmp.MaLoaiCongThuc = this.MaLoaiCongThuc;
			_tmp.NamHoc = this.NamHoc;
			_tmp.HocKy = this.HocKy;
			_tmp.CongThuc = this.CongThuc;
			_tmp.ToanHangSuDung = this.ToanHangSuDung;
			_tmp.ApDung = this.ApDung;
			_tmp.DienGiai = this.DienGiai;
			_tmp.TinhVuotDinhMuc = this.TinhVuotDinhMuc;
			_tmp.TinhVuotTran = this.TinhVuotTran;
			
			#region Source Parent Composite Entities
			if (this.MaLoaiCongThucSource != null)
				_tmp.MaLoaiCongThucSource = MakeCopyOf(this.MaLoaiCongThucSource) as LoaiCongThuc;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			CongThucTinhQuyDoiEntityData _tmp = new CongThucTinhQuyDoiEntityData();
						
			_tmp.MaCongThuc = this.MaCongThuc;
			
			_tmp.MaLoaiCongThuc = this.MaLoaiCongThuc;
			_tmp.NamHoc = this.NamHoc;
			_tmp.HocKy = this.HocKy;
			_tmp.CongThuc = this.CongThuc;
			_tmp.ToanHangSuDung = this.ToanHangSuDung;
			_tmp.ApDung = this.ApDung;
			_tmp.DienGiai = this.DienGiai;
			_tmp.TinhVuotDinhMuc = this.TinhVuotDinhMuc;
			_tmp.TinhVuotTran = this.TinhVuotTran;
			
			#region Source Parent Composite Entities
			if (this.MaLoaiCongThucSource != null && existingCopies.Contains(this.MaLoaiCongThucSource))
				_tmp.MaLoaiCongThucSource = existingCopies[this.MaLoaiCongThucSource] as LoaiCongThuc;
			else
				_tmp.MaLoaiCongThucSource = MakeCopyOf(this.MaLoaiCongThucSource, existingCopies) as LoaiCongThuc;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false)]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CongThucTinhQuyDoiColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(CongThucTinhQuyDoiColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CongThucTinhQuyDoiColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(CongThucTinhQuyDoiColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CongThucTinhQuyDoiColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(CongThucTinhQuyDoiColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				CongThucTinhQuyDoiEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new CongThucTinhQuyDoiEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CongThucTinhQuyDoiColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(CongThucTinhQuyDoiColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				CongThucTinhQuyDoiEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new CongThucTinhQuyDoiEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region CongThucTinhQuyDoiEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="CongThucTinhQuyDoi"/> object.
	/// </remarks>
	public class CongThucTinhQuyDoiEventArgs : System.EventArgs
	{
		private CongThucTinhQuyDoiColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the CongThucTinhQuyDoiEventArgs class.
		///</summary>
		public CongThucTinhQuyDoiEventArgs(CongThucTinhQuyDoiColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the CongThucTinhQuyDoiEventArgs class.
		///</summary>
		public CongThucTinhQuyDoiEventArgs(CongThucTinhQuyDoiColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The CongThucTinhQuyDoiColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="CongThucTinhQuyDoiColumn" />
		public CongThucTinhQuyDoiColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all CongThucTinhQuyDoi related events.
	///</summary>
	public delegate void CongThucTinhQuyDoiEventHandler(object sender, CongThucTinhQuyDoiEventArgs e);
	
	#region CongThucTinhQuyDoiComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class CongThucTinhQuyDoiComparer : System.Collections.Generic.IComparer<CongThucTinhQuyDoi>
	{
		CongThucTinhQuyDoiColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:CongThucTinhQuyDoiComparer"/> class.
        /// </summary>
		public CongThucTinhQuyDoiComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:CongThucTinhQuyDoiComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public CongThucTinhQuyDoiComparer(CongThucTinhQuyDoiColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="CongThucTinhQuyDoi"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="CongThucTinhQuyDoi"/> to compare.</param>
        /// <param name="b">The second <c>CongThucTinhQuyDoi</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(CongThucTinhQuyDoi a, CongThucTinhQuyDoi b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(CongThucTinhQuyDoi entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(CongThucTinhQuyDoi a, CongThucTinhQuyDoi b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public CongThucTinhQuyDoiColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region CongThucTinhQuyDoiKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="CongThucTinhQuyDoi"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class CongThucTinhQuyDoiKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the CongThucTinhQuyDoiKey class.
		/// </summary>
		public CongThucTinhQuyDoiKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the CongThucTinhQuyDoiKey class.
		/// </summary>
		public CongThucTinhQuyDoiKey(CongThucTinhQuyDoiBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MaCongThuc = entity.MaCongThuc;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the CongThucTinhQuyDoiKey class.
		/// </summary>
		public CongThucTinhQuyDoiKey(System.Int32 _maCongThuc)
		{
			#region Init Properties

			this.MaCongThuc = _maCongThuc;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private CongThucTinhQuyDoiBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public CongThucTinhQuyDoiBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MaCongThuc property
		private System.Int32 _maCongThuc;
		
		/// <summary>
		/// Gets or sets the MaCongThuc property.
		/// </summary>
		public System.Int32 MaCongThuc
		{
			get { return _maCongThuc; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MaCongThuc = value;
				
				_maCongThuc = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MaCongThuc = ( values["MaCongThuc"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["MaCongThuc"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MaCongThuc", MaCongThuc);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MaCongThuc: {0}{1}",
								MaCongThuc,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region CongThucTinhQuyDoiColumn Enum
	
	/// <summary>
	/// Enumerate the CongThucTinhQuyDoi columns.
	/// </summary>
	[Serializable]
	public enum CongThucTinhQuyDoiColumn : int
	{
		/// <summary>
		/// MaCongThuc : 
		/// </summary>
		[EnumTextValue("Ma Cong Thuc")]
		[ColumnEnum("MaCongThuc", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		MaCongThuc = 1,
		/// <summary>
		/// MaLoaiCongThuc : 
		/// </summary>
		[EnumTextValue("Ma Loai Cong Thuc")]
		[ColumnEnum("MaLoaiCongThuc", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		MaLoaiCongThuc = 2,
		/// <summary>
		/// NamHoc : 
		/// </summary>
		[EnumTextValue("Nam Hoc")]
		[ColumnEnum("NamHoc", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		NamHoc = 3,
		/// <summary>
		/// HocKy : 
		/// </summary>
		[EnumTextValue("Hoc Ky")]
		[ColumnEnum("HocKy", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		HocKy = 4,
		/// <summary>
		/// CongThuc : 
		/// </summary>
		[EnumTextValue("Cong Thuc")]
		[ColumnEnum("CongThuc", typeof(System.String), System.Data.DbType.String, false, false, false)]
		CongThuc = 5,
		/// <summary>
		/// ToanHangSuDung : 
		/// </summary>
		[EnumTextValue("Toan Hang Su Dung")]
		[ColumnEnum("ToanHangSuDung", typeof(System.String), System.Data.DbType.String, false, false, false)]
		ToanHangSuDung = 6,
		/// <summary>
		/// ApDung : 
		/// </summary>
		[EnumTextValue("Ap Dung")]
		[ColumnEnum("ApDung", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		ApDung = 7,
		/// <summary>
		/// DienGiai : 
		/// </summary>
		[EnumTextValue("Dien Giai")]
		[ColumnEnum("DienGiai", typeof(System.String), System.Data.DbType.String, false, false, true)]
		DienGiai = 8,
		/// <summary>
		/// TinhVuotDinhMuc : 
		/// </summary>
		[EnumTextValue("Tinh Vuot Dinh Muc")]
		[ColumnEnum("TinhVuotDinhMuc", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		TinhVuotDinhMuc = 9,
		/// <summary>
		/// TinhVuotTran : 
		/// </summary>
		[EnumTextValue("Tinh Vuot Tran")]
		[ColumnEnum("TinhVuotTran", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		TinhVuotTran = 10
	}//End enum

	#endregion CongThucTinhQuyDoiColumn Enum

} // end namespace
