
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file CongThucTinhHeSo.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using PMS.Entities.Validation;
#endregion

namespace PMS.Entities
{
	///<summary>
	/// An object representation of the 'CongThucTinhHeSo' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class CongThucTinhHeSoBase : EntityBase, ICongThucTinhHeSo, IEntityId<CongThucTinhHeSoKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private CongThucTinhHeSoEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private CongThucTinhHeSoEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private CongThucTinhHeSoEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<CongThucTinhHeSo> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CongThucTinhHeSoEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CongThucTinhHeSoEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="CongThucTinhHeSoBase"/> instance.
		///</summary>
		public CongThucTinhHeSoBase()
		{
			this.entityData = new CongThucTinhHeSoEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="CongThucTinhHeSoBase"/> instance.
		///</summary>
		///<param name="_maLoaiHeSo"></param>
		///<param name="_maHeSoTinhCongThuc"></param>
		///<param name="_tenHienThiCongThuc"></param>
		///<param name="_thamSoDauVao"></param>
		///<param name="_cotCanTinh"></param>
		///<param name="_apDung"></param>
		///<param name="_toanTu"></param>
		///<param name="_defaultValue"></param>
		public CongThucTinhHeSoBase(System.Int32? _maLoaiHeSo, System.String _maHeSoTinhCongThuc, 
			System.String _tenHienThiCongThuc, System.String _thamSoDauVao, System.String _cotCanTinh, 
			System.Boolean? _apDung, System.String _toanTu, System.Decimal? _defaultValue)
		{
			this.entityData = new CongThucTinhHeSoEntityData();
			this.backupData = null;

			this.MaLoaiHeSo = _maLoaiHeSo;
			this.MaHeSoTinhCongThuc = _maHeSoTinhCongThuc;
			this.TenHienThiCongThuc = _tenHienThiCongThuc;
			this.ThamSoDauVao = _thamSoDauVao;
			this.CotCanTinh = _cotCanTinh;
			this.ApDung = _apDung;
			this.ToanTu = _toanTu;
			this.DefaultValue = _defaultValue;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="CongThucTinhHeSo"/> instance.
		///</summary>
		///<param name="_maLoaiHeSo"></param>
		///<param name="_maHeSoTinhCongThuc"></param>
		///<param name="_tenHienThiCongThuc"></param>
		///<param name="_thamSoDauVao"></param>
		///<param name="_cotCanTinh"></param>
		///<param name="_apDung"></param>
		///<param name="_toanTu"></param>
		///<param name="_defaultValue"></param>
		public static CongThucTinhHeSo CreateCongThucTinhHeSo(System.Int32? _maLoaiHeSo, System.String _maHeSoTinhCongThuc, 
			System.String _tenHienThiCongThuc, System.String _thamSoDauVao, System.String _cotCanTinh, 
			System.Boolean? _apDung, System.String _toanTu, System.Decimal? _defaultValue)
		{
			CongThucTinhHeSo newCongThucTinhHeSo = new CongThucTinhHeSo();
			newCongThucTinhHeSo.MaLoaiHeSo = _maLoaiHeSo;
			newCongThucTinhHeSo.MaHeSoTinhCongThuc = _maHeSoTinhCongThuc;
			newCongThucTinhHeSo.TenHienThiCongThuc = _tenHienThiCongThuc;
			newCongThucTinhHeSo.ThamSoDauVao = _thamSoDauVao;
			newCongThucTinhHeSo.CotCanTinh = _cotCanTinh;
			newCongThucTinhHeSo.ApDung = _apDung;
			newCongThucTinhHeSo.ToanTu = _toanTu;
			newCongThucTinhHeSo.DefaultValue = _defaultValue;
			return newCongThucTinhHeSo;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(CongThucTinhHeSoColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhHeSoColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaLoaiHeSo property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? MaLoaiHeSo
		{
			get
			{
				return this.entityData.MaLoaiHeSo; 
			}
			
			set
			{
				if (this.entityData.MaLoaiHeSo == value)
					return;
				
                OnPropertyChanging("MaLoaiHeSo");                    
				OnColumnChanging(CongThucTinhHeSoColumn.MaLoaiHeSo, this.entityData.MaLoaiHeSo);
				this.entityData.MaLoaiHeSo = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhHeSoColumn.MaLoaiHeSo, this.entityData.MaLoaiHeSo);
				OnPropertyChanged("MaLoaiHeSo");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaHeSoTinhCongThuc property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String MaHeSoTinhCongThuc
		{
			get
			{
				return this.entityData.MaHeSoTinhCongThuc; 
			}
			
			set
			{
				if (this.entityData.MaHeSoTinhCongThuc == value)
					return;
				
                OnPropertyChanging("MaHeSoTinhCongThuc");                    
				OnColumnChanging(CongThucTinhHeSoColumn.MaHeSoTinhCongThuc, this.entityData.MaHeSoTinhCongThuc);
				this.entityData.MaHeSoTinhCongThuc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhHeSoColumn.MaHeSoTinhCongThuc, this.entityData.MaHeSoTinhCongThuc);
				OnPropertyChanged("MaHeSoTinhCongThuc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TenHienThiCongThuc property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public virtual System.String TenHienThiCongThuc
		{
			get
			{
				return this.entityData.TenHienThiCongThuc; 
			}
			
			set
			{
				if (this.entityData.TenHienThiCongThuc == value)
					return;
				
                OnPropertyChanging("TenHienThiCongThuc");                    
				OnColumnChanging(CongThucTinhHeSoColumn.TenHienThiCongThuc, this.entityData.TenHienThiCongThuc);
				this.entityData.TenHienThiCongThuc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhHeSoColumn.TenHienThiCongThuc, this.entityData.TenHienThiCongThuc);
				OnPropertyChanged("TenHienThiCongThuc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ThamSoDauVao property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 1000)]
		public virtual System.String ThamSoDauVao
		{
			get
			{
				return this.entityData.ThamSoDauVao; 
			}
			
			set
			{
				if (this.entityData.ThamSoDauVao == value)
					return;
				
                OnPropertyChanging("ThamSoDauVao");                    
				OnColumnChanging(CongThucTinhHeSoColumn.ThamSoDauVao, this.entityData.ThamSoDauVao);
				this.entityData.ThamSoDauVao = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhHeSoColumn.ThamSoDauVao, this.entityData.ThamSoDauVao);
				OnPropertyChanged("ThamSoDauVao");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CotCanTinh property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 100)]
		public virtual System.String CotCanTinh
		{
			get
			{
				return this.entityData.CotCanTinh; 
			}
			
			set
			{
				if (this.entityData.CotCanTinh == value)
					return;
				
                OnPropertyChanging("CotCanTinh");                    
				OnColumnChanging(CongThucTinhHeSoColumn.CotCanTinh, this.entityData.CotCanTinh);
				this.entityData.CotCanTinh = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhHeSoColumn.CotCanTinh, this.entityData.CotCanTinh);
				OnPropertyChanged("CotCanTinh");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ApDung property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? ApDung
		{
			get
			{
				return this.entityData.ApDung; 
			}
			
			set
			{
				if (this.entityData.ApDung == value)
					return;
				
                OnPropertyChanging("ApDung");                    
				OnColumnChanging(CongThucTinhHeSoColumn.ApDung, this.entityData.ApDung);
				this.entityData.ApDung = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhHeSoColumn.ApDung, this.entityData.ApDung);
				OnPropertyChanged("ApDung");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ToanTu property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public virtual System.String ToanTu
		{
			get
			{
				return this.entityData.ToanTu; 
			}
			
			set
			{
				if (this.entityData.ToanTu == value)
					return;
				
                OnPropertyChanging("ToanTu");                    
				OnColumnChanging(CongThucTinhHeSoColumn.ToanTu, this.entityData.ToanTu);
				this.entityData.ToanTu = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhHeSoColumn.ToanTu, this.entityData.ToanTu);
				OnPropertyChanged("ToanTu");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DefaultValue property. 
		///		
		/// </summary>
		/// <value>This type is decimal.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? DefaultValue
		{
			get
			{
				return this.entityData.DefaultValue; 
			}
			
			set
			{
				if (this.entityData.DefaultValue == value)
					return;
				
                OnPropertyChanging("DefaultValue");                    
				OnColumnChanging(CongThucTinhHeSoColumn.DefaultValue, this.entityData.DefaultValue);
				this.entityData.DefaultValue = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CongThucTinhHeSoColumn.DefaultValue, this.entityData.DefaultValue);
				OnPropertyChanged("DefaultValue");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="LoaiHeSoTinhThuLao"/>.
		/// </summary>
		/// <value>The source LoaiHeSoTinhThuLao for MaLoaiHeSo.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual LoaiHeSoTinhThuLao MaLoaiHeSoSource
      	{
            get { return entityData.MaLoaiHeSoSource; }
            set { entityData.MaLoaiHeSoSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("MaHeSoTinhCongThuc", "Ma He So Tinh Cong Thuc", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("TenHienThiCongThuc", "Ten Hien Thi Cong Thuc", 200));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("ThamSoDauVao", "Tham So Dau Vao", 1000));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("CotCanTinh", "Cot Can Tinh", 100));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("ToanTu", "Toan Tu", 200));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "CongThucTinhHeSo"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID", "MaLoaiHeSo", "MaHeSoTinhCongThuc", "TenHienThiCongThuc", "ThamSoDauVao", "CotCanTinh", "ApDung", "ToanTu", "DefaultValue"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as CongThucTinhHeSoEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (CongThucTinhHeSo) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<CongThucTinhHeSo>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as CongThucTinhHeSo);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed CongThucTinhHeSo Entity 
		///</summary>
		protected virtual CongThucTinhHeSo Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			CongThucTinhHeSo copy = new CongThucTinhHeSo();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.MaLoaiHeSo = this.MaLoaiHeSo;
				copy.MaHeSoTinhCongThuc = this.MaHeSoTinhCongThuc;
				copy.TenHienThiCongThuc = this.TenHienThiCongThuc;
				copy.ThamSoDauVao = this.ThamSoDauVao;
				copy.CotCanTinh = this.CotCanTinh;
				copy.ApDung = this.ApDung;
				copy.ToanTu = this.ToanTu;
				copy.DefaultValue = this.DefaultValue;
			
			if (this.MaLoaiHeSoSource != null && existingCopies.Contains(this.MaLoaiHeSoSource))
				copy.MaLoaiHeSoSource = existingCopies[this.MaLoaiHeSoSource] as LoaiHeSoTinhThuLao;
			else
				copy.MaLoaiHeSoSource = MakeCopyOf(this.MaLoaiHeSoSource, existingCopies) as LoaiHeSoTinhThuLao;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed CongThucTinhHeSo Entity 
		///</summary>
		public virtual CongThucTinhHeSo Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed CongThucTinhHeSo Entity which is a deep copy of the current entity.
		///</summary>
		public virtual CongThucTinhHeSo DeepCopy()
		{
			return EntityHelper.Clone<CongThucTinhHeSo>(this as CongThucTinhHeSo);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as CongThucTinhHeSoEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new CongThucTinhHeSoEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as CongThucTinhHeSoEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(CongThucTinhHeSoColumn column)
		{
			switch(column)
			{
					case CongThucTinhHeSoColumn.Id:
					return entityData.Id != _originalData.Id;
					case CongThucTinhHeSoColumn.MaLoaiHeSo:
					return entityData.MaLoaiHeSo != _originalData.MaLoaiHeSo;
					case CongThucTinhHeSoColumn.MaHeSoTinhCongThuc:
					return entityData.MaHeSoTinhCongThuc != _originalData.MaHeSoTinhCongThuc;
					case CongThucTinhHeSoColumn.TenHienThiCongThuc:
					return entityData.TenHienThiCongThuc != _originalData.TenHienThiCongThuc;
					case CongThucTinhHeSoColumn.ThamSoDauVao:
					return entityData.ThamSoDauVao != _originalData.ThamSoDauVao;
					case CongThucTinhHeSoColumn.CotCanTinh:
					return entityData.CotCanTinh != _originalData.CotCanTinh;
					case CongThucTinhHeSoColumn.ApDung:
					return entityData.ApDung != _originalData.ApDung;
					case CongThucTinhHeSoColumn.ToanTu:
					return entityData.ToanTu != _originalData.ToanTu;
					case CongThucTinhHeSoColumn.DefaultValue:
					return entityData.DefaultValue != _originalData.DefaultValue;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< CongThucTinhHeSoColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.MaLoaiHeSo != _originalData.MaLoaiHeSo;
			result = result || entityData.MaHeSoTinhCongThuc != _originalData.MaHeSoTinhCongThuc;
			result = result || entityData.TenHienThiCongThuc != _originalData.TenHienThiCongThuc;
			result = result || entityData.ThamSoDauVao != _originalData.ThamSoDauVao;
			result = result || entityData.CotCanTinh != _originalData.CotCanTinh;
			result = result || entityData.ApDung != _originalData.ApDung;
			result = result || entityData.ToanTu != _originalData.ToanTu;
			result = result || entityData.DefaultValue != _originalData.DefaultValue;
			return result;
		}	
		
		///<summary>
		///  Returns a CongThucTinhHeSo Entity with the original data.
		///</summary>
		public CongThucTinhHeSo GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateCongThucTinhHeSo(
				_originalData.MaLoaiHeSo,
				_originalData.MaHeSoTinhCongThuc,
				_originalData.TenHienThiCongThuc,
				_originalData.ThamSoDauVao,
				_originalData.CotCanTinh,
				_originalData.ApDung,
				_originalData.ToanTu,
				_originalData.DefaultValue
				);
				
			return (CongThucTinhHeSo)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="CongThucTinhHeSoBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is CongThucTinhHeSoBase)
				return ValueEquals(this, (CongThucTinhHeSoBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="CongThucTinhHeSoBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.MaLoaiHeSo == null) ? string.Empty : this.MaLoaiHeSo.ToString()).GetHashCode() ^ 
					((this.MaHeSoTinhCongThuc == null) ? string.Empty : this.MaHeSoTinhCongThuc.ToString()).GetHashCode() ^ 
					((this.TenHienThiCongThuc == null) ? string.Empty : this.TenHienThiCongThuc.ToString()).GetHashCode() ^ 
					((this.ThamSoDauVao == null) ? string.Empty : this.ThamSoDauVao.ToString()).GetHashCode() ^ 
					((this.CotCanTinh == null) ? string.Empty : this.CotCanTinh.ToString()).GetHashCode() ^ 
					((this.ApDung == null) ? string.Empty : this.ApDung.ToString()).GetHashCode() ^ 
					((this.ToanTu == null) ? string.Empty : this.ToanTu.ToString()).GetHashCode() ^ 
					((this.DefaultValue == null) ? string.Empty : this.DefaultValue.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="CongThucTinhHeSoBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(CongThucTinhHeSoBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="CongThucTinhHeSoBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="CongThucTinhHeSoBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="CongThucTinhHeSoBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(CongThucTinhHeSoBase Object1, CongThucTinhHeSoBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.MaLoaiHeSo != null && Object2.MaLoaiHeSo != null )
			{
				if (Object1.MaLoaiHeSo != Object2.MaLoaiHeSo)
					equal = false;
			}
			else if (Object1.MaLoaiHeSo == null ^ Object2.MaLoaiHeSo == null )
			{
				equal = false;
			}
			if ( Object1.MaHeSoTinhCongThuc != null && Object2.MaHeSoTinhCongThuc != null )
			{
				if (Object1.MaHeSoTinhCongThuc != Object2.MaHeSoTinhCongThuc)
					equal = false;
			}
			else if (Object1.MaHeSoTinhCongThuc == null ^ Object2.MaHeSoTinhCongThuc == null )
			{
				equal = false;
			}
			if ( Object1.TenHienThiCongThuc != null && Object2.TenHienThiCongThuc != null )
			{
				if (Object1.TenHienThiCongThuc != Object2.TenHienThiCongThuc)
					equal = false;
			}
			else if (Object1.TenHienThiCongThuc == null ^ Object2.TenHienThiCongThuc == null )
			{
				equal = false;
			}
			if ( Object1.ThamSoDauVao != null && Object2.ThamSoDauVao != null )
			{
				if (Object1.ThamSoDauVao != Object2.ThamSoDauVao)
					equal = false;
			}
			else if (Object1.ThamSoDauVao == null ^ Object2.ThamSoDauVao == null )
			{
				equal = false;
			}
			if ( Object1.CotCanTinh != null && Object2.CotCanTinh != null )
			{
				if (Object1.CotCanTinh != Object2.CotCanTinh)
					equal = false;
			}
			else if (Object1.CotCanTinh == null ^ Object2.CotCanTinh == null )
			{
				equal = false;
			}
			if ( Object1.ApDung != null && Object2.ApDung != null )
			{
				if (Object1.ApDung != Object2.ApDung)
					equal = false;
			}
			else if (Object1.ApDung == null ^ Object2.ApDung == null )
			{
				equal = false;
			}
			if ( Object1.ToanTu != null && Object2.ToanTu != null )
			{
				if (Object1.ToanTu != Object2.ToanTu)
					equal = false;
			}
			else if (Object1.ToanTu == null ^ Object2.ToanTu == null )
			{
				equal = false;
			}
			if ( Object1.DefaultValue != null && Object2.DefaultValue != null )
			{
				if (Object1.DefaultValue != Object2.DefaultValue)
					equal = false;
			}
			else if (Object1.DefaultValue == null ^ Object2.DefaultValue == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((CongThucTinhHeSoBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static CongThucTinhHeSoComparer GetComparer()
        {
            return new CongThucTinhHeSoComparer();
        }
        */

        // Comparer delegates back to CongThucTinhHeSo
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(CongThucTinhHeSo rhs, CongThucTinhHeSoColumn which)
        {
            switch (which)
            {
            	
            	
            	case CongThucTinhHeSoColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case CongThucTinhHeSoColumn.MaLoaiHeSo:
            		return this.MaLoaiHeSo.Value.CompareTo(rhs.MaLoaiHeSo.Value);
            		
            		                 
            	
            	
            	case CongThucTinhHeSoColumn.MaHeSoTinhCongThuc:
            		return this.MaHeSoTinhCongThuc.CompareTo(rhs.MaHeSoTinhCongThuc);
            		
            		                 
            	
            	
            	case CongThucTinhHeSoColumn.TenHienThiCongThuc:
            		return this.TenHienThiCongThuc.CompareTo(rhs.TenHienThiCongThuc);
            		
            		                 
            	
            	
            	case CongThucTinhHeSoColumn.ThamSoDauVao:
            		return this.ThamSoDauVao.CompareTo(rhs.ThamSoDauVao);
            		
            		                 
            	
            	
            	case CongThucTinhHeSoColumn.CotCanTinh:
            		return this.CotCanTinh.CompareTo(rhs.CotCanTinh);
            		
            		                 
            	
            	
            	case CongThucTinhHeSoColumn.ApDung:
            		return this.ApDung.Value.CompareTo(rhs.ApDung.Value);
            		
            		                 
            	
            	
            	case CongThucTinhHeSoColumn.ToanTu:
            		return this.ToanTu.CompareTo(rhs.ToanTu);
            		
            		                 
            	
            	
            	case CongThucTinhHeSoColumn.DefaultValue:
            		return this.DefaultValue.Value.CompareTo(rhs.DefaultValue.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<CongThucTinhHeSoKey> Members
		
		// member variable for the EntityId property
		private CongThucTinhHeSoKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual CongThucTinhHeSoKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new CongThucTinhHeSoKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) ]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("CongThucTinhHeSo")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{10}{9}- Id: {0}{9}- MaLoaiHeSo: {1}{9}- MaHeSoTinhCongThuc: {2}{9}- TenHienThiCongThuc: {3}{9}- ThamSoDauVao: {4}{9}- CotCanTinh: {5}{9}- ApDung: {6}{9}- ToanTu: {7}{9}- DefaultValue: {8}{9}{11}", 
				this.Id,
				(this.MaLoaiHeSo == null) ? string.Empty : this.MaLoaiHeSo.ToString(),
				(this.MaHeSoTinhCongThuc == null) ? string.Empty : this.MaHeSoTinhCongThuc.ToString(),
				(this.TenHienThiCongThuc == null) ? string.Empty : this.TenHienThiCongThuc.ToString(),
				(this.ThamSoDauVao == null) ? string.Empty : this.ThamSoDauVao.ToString(),
				(this.CotCanTinh == null) ? string.Empty : this.CotCanTinh.ToString(),
				(this.ApDung == null) ? string.Empty : this.ApDung.ToString(),
				(this.ToanTu == null) ? string.Empty : this.ToanTu.ToString(),
				(this.DefaultValue == null) ? string.Empty : this.DefaultValue.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'CongThucTinhHeSo' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class CongThucTinhHeSoEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "CongThucTinhHeSo"</remarks>
		public System.Int32 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// MaLoaiHeSo : 
		/// </summary>
		public System.Int32? MaLoaiHeSo = null;
		
		/// <summary>
		/// MaHeSoTinhCongThuc : 
		/// </summary>
		public System.String MaHeSoTinhCongThuc = null;
		
		/// <summary>
		/// TenHienThiCongThuc : 
		/// </summary>
		public System.String TenHienThiCongThuc = null;
		
		/// <summary>
		/// ThamSoDauVao : 
		/// </summary>
		public System.String ThamSoDauVao = null;
		
		/// <summary>
		/// CotCanTinh : 
		/// </summary>
		public System.String CotCanTinh = null;
		
		/// <summary>
		/// ApDung : 
		/// </summary>
		public System.Boolean? ApDung = null;
		
		/// <summary>
		/// ToanTu : 
		/// </summary>
		public System.String ToanTu = null;
		
		/// <summary>
		/// DefaultValue : 
		/// </summary>
		public System.Decimal? DefaultValue = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private LoaiHeSoTinhThuLao _maLoaiHeSoSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="LoaiHeSoTinhThuLao"/>.
		/// </summary>
		/// <value>The source LoaiHeSoTinhThuLao for MaLoaiHeSo.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual LoaiHeSoTinhThuLao MaLoaiHeSoSource
      	{
            get { return this._maLoaiHeSoSource; }
            set { this._maLoaiHeSoSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			CongThucTinhHeSoEntityData _tmp = new CongThucTinhHeSoEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.MaLoaiHeSo = this.MaLoaiHeSo;
			_tmp.MaHeSoTinhCongThuc = this.MaHeSoTinhCongThuc;
			_tmp.TenHienThiCongThuc = this.TenHienThiCongThuc;
			_tmp.ThamSoDauVao = this.ThamSoDauVao;
			_tmp.CotCanTinh = this.CotCanTinh;
			_tmp.ApDung = this.ApDung;
			_tmp.ToanTu = this.ToanTu;
			_tmp.DefaultValue = this.DefaultValue;
			
			#region Source Parent Composite Entities
			if (this.MaLoaiHeSoSource != null)
				_tmp.MaLoaiHeSoSource = MakeCopyOf(this.MaLoaiHeSoSource) as LoaiHeSoTinhThuLao;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			CongThucTinhHeSoEntityData _tmp = new CongThucTinhHeSoEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.MaLoaiHeSo = this.MaLoaiHeSo;
			_tmp.MaHeSoTinhCongThuc = this.MaHeSoTinhCongThuc;
			_tmp.TenHienThiCongThuc = this.TenHienThiCongThuc;
			_tmp.ThamSoDauVao = this.ThamSoDauVao;
			_tmp.CotCanTinh = this.CotCanTinh;
			_tmp.ApDung = this.ApDung;
			_tmp.ToanTu = this.ToanTu;
			_tmp.DefaultValue = this.DefaultValue;
			
			#region Source Parent Composite Entities
			if (this.MaLoaiHeSoSource != null && existingCopies.Contains(this.MaLoaiHeSoSource))
				_tmp.MaLoaiHeSoSource = existingCopies[this.MaLoaiHeSoSource] as LoaiHeSoTinhThuLao;
			else
				_tmp.MaLoaiHeSoSource = MakeCopyOf(this.MaLoaiHeSoSource, existingCopies) as LoaiHeSoTinhThuLao;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false)]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CongThucTinhHeSoColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(CongThucTinhHeSoColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CongThucTinhHeSoColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(CongThucTinhHeSoColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CongThucTinhHeSoColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(CongThucTinhHeSoColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				CongThucTinhHeSoEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new CongThucTinhHeSoEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CongThucTinhHeSoColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(CongThucTinhHeSoColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				CongThucTinhHeSoEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new CongThucTinhHeSoEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region CongThucTinhHeSoEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="CongThucTinhHeSo"/> object.
	/// </remarks>
	public class CongThucTinhHeSoEventArgs : System.EventArgs
	{
		private CongThucTinhHeSoColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the CongThucTinhHeSoEventArgs class.
		///</summary>
		public CongThucTinhHeSoEventArgs(CongThucTinhHeSoColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the CongThucTinhHeSoEventArgs class.
		///</summary>
		public CongThucTinhHeSoEventArgs(CongThucTinhHeSoColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The CongThucTinhHeSoColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="CongThucTinhHeSoColumn" />
		public CongThucTinhHeSoColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all CongThucTinhHeSo related events.
	///</summary>
	public delegate void CongThucTinhHeSoEventHandler(object sender, CongThucTinhHeSoEventArgs e);
	
	#region CongThucTinhHeSoComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class CongThucTinhHeSoComparer : System.Collections.Generic.IComparer<CongThucTinhHeSo>
	{
		CongThucTinhHeSoColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:CongThucTinhHeSoComparer"/> class.
        /// </summary>
		public CongThucTinhHeSoComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:CongThucTinhHeSoComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public CongThucTinhHeSoComparer(CongThucTinhHeSoColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="CongThucTinhHeSo"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="CongThucTinhHeSo"/> to compare.</param>
        /// <param name="b">The second <c>CongThucTinhHeSo</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(CongThucTinhHeSo a, CongThucTinhHeSo b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(CongThucTinhHeSo entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(CongThucTinhHeSo a, CongThucTinhHeSo b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public CongThucTinhHeSoColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region CongThucTinhHeSoKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="CongThucTinhHeSo"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class CongThucTinhHeSoKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the CongThucTinhHeSoKey class.
		/// </summary>
		public CongThucTinhHeSoKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the CongThucTinhHeSoKey class.
		/// </summary>
		public CongThucTinhHeSoKey(CongThucTinhHeSoBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the CongThucTinhHeSoKey class.
		/// </summary>
		public CongThucTinhHeSoKey(System.Int32 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private CongThucTinhHeSoBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public CongThucTinhHeSoBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int32 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int32 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Id"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region CongThucTinhHeSoColumn Enum
	
	/// <summary>
	/// Enumerate the CongThucTinhHeSo columns.
	/// </summary>
	[Serializable]
	public enum CongThucTinhHeSoColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		Id = 1,
		/// <summary>
		/// MaLoaiHeSo : 
		/// </summary>
		[EnumTextValue("Ma Loai He So")]
		[ColumnEnum("MaLoaiHeSo", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		MaLoaiHeSo = 2,
		/// <summary>
		/// MaHeSoTinhCongThuc : 
		/// </summary>
		[EnumTextValue("Ma He So Tinh Cong Thuc")]
		[ColumnEnum("MaHeSoTinhCongThuc", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		MaHeSoTinhCongThuc = 3,
		/// <summary>
		/// TenHienThiCongThuc : 
		/// </summary>
		[EnumTextValue("Ten Hien Thi Cong Thuc")]
		[ColumnEnum("TenHienThiCongThuc", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		TenHienThiCongThuc = 4,
		/// <summary>
		/// ThamSoDauVao : 
		/// </summary>
		[EnumTextValue("Tham So Dau Vao")]
		[ColumnEnum("ThamSoDauVao", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 1000)]
		ThamSoDauVao = 5,
		/// <summary>
		/// CotCanTinh : 
		/// </summary>
		[EnumTextValue("Cot Can Tinh")]
		[ColumnEnum("CotCanTinh", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 100)]
		CotCanTinh = 6,
		/// <summary>
		/// ApDung : 
		/// </summary>
		[EnumTextValue("Ap Dung")]
		[ColumnEnum("ApDung", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		ApDung = 7,
		/// <summary>
		/// ToanTu : 
		/// </summary>
		[EnumTextValue("Toan Tu")]
		[ColumnEnum("ToanTu", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 200)]
		ToanTu = 8,
		/// <summary>
		/// DefaultValue : 
		/// </summary>
		[EnumTextValue("Default Value")]
		[ColumnEnum("DefaultValue", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		DefaultValue = 9
	}//End enum

	#endregion CongThucTinhHeSoColumn Enum

} // end namespace
