
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file DieuKhoanBaoCao.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using PMS.Entities.Validation;
#endregion

namespace PMS.Entities
{
	///<summary>
	/// An object representation of the 'DieuKhoanBaoCao' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class DieuKhoanBaoCaoBase : EntityBase, IDieuKhoanBaoCao, IEntityId<DieuKhoanBaoCaoKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private DieuKhoanBaoCaoEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private DieuKhoanBaoCaoEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private DieuKhoanBaoCaoEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<DieuKhoanBaoCao> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DieuKhoanBaoCaoEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DieuKhoanBaoCaoEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="DieuKhoanBaoCaoBase"/> instance.
		///</summary>
		public DieuKhoanBaoCaoBase()
		{
			this.entityData = new DieuKhoanBaoCaoEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="DieuKhoanBaoCaoBase"/> instance.
		///</summary>
		///<param name="_parentId"></param>
		///<param name="_phanLoai"></param>
		///<param name="_idChucNang"></param>
		///<param name="_noiDung"></param>
		///<param name="_thuTu"></param>
		///<param name="_ngayCapNhat"></param>
		///<param name="_nguoiCapNhat"></param>
		///<param name="_namHoc"></param>
		///<param name="_hocKy"></param>
		///<param name="_ghiChu"></param>
		///<param name="_trangThai"></param>
		public DieuKhoanBaoCaoBase(System.Int32? _parentId, System.String _phanLoai, System.Int32? _idChucNang, 
			System.String _noiDung, System.Int32? _thuTu, System.String _ngayCapNhat, System.String _nguoiCapNhat, 
			System.String _namHoc, System.String _hocKy, System.String _ghiChu, System.Boolean? _trangThai)
		{
			this.entityData = new DieuKhoanBaoCaoEntityData();
			this.backupData = null;

			this.ParentId = _parentId;
			this.PhanLoai = _phanLoai;
			this.IdChucNang = _idChucNang;
			this.NoiDung = _noiDung;
			this.ThuTu = _thuTu;
			this.NgayCapNhat = _ngayCapNhat;
			this.NguoiCapNhat = _nguoiCapNhat;
			this.NamHoc = _namHoc;
			this.HocKy = _hocKy;
			this.GhiChu = _ghiChu;
			this.TrangThai = _trangThai;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="DieuKhoanBaoCao"/> instance.
		///</summary>
		///<param name="_parentId"></param>
		///<param name="_phanLoai"></param>
		///<param name="_idChucNang"></param>
		///<param name="_noiDung"></param>
		///<param name="_thuTu"></param>
		///<param name="_ngayCapNhat"></param>
		///<param name="_nguoiCapNhat"></param>
		///<param name="_namHoc"></param>
		///<param name="_hocKy"></param>
		///<param name="_ghiChu"></param>
		///<param name="_trangThai"></param>
		public static DieuKhoanBaoCao CreateDieuKhoanBaoCao(System.Int32? _parentId, System.String _phanLoai, System.Int32? _idChucNang, 
			System.String _noiDung, System.Int32? _thuTu, System.String _ngayCapNhat, System.String _nguoiCapNhat, 
			System.String _namHoc, System.String _hocKy, System.String _ghiChu, System.Boolean? _trangThai)
		{
			DieuKhoanBaoCao newDieuKhoanBaoCao = new DieuKhoanBaoCao();
			newDieuKhoanBaoCao.ParentId = _parentId;
			newDieuKhoanBaoCao.PhanLoai = _phanLoai;
			newDieuKhoanBaoCao.IdChucNang = _idChucNang;
			newDieuKhoanBaoCao.NoiDung = _noiDung;
			newDieuKhoanBaoCao.ThuTu = _thuTu;
			newDieuKhoanBaoCao.NgayCapNhat = _ngayCapNhat;
			newDieuKhoanBaoCao.NguoiCapNhat = _nguoiCapNhat;
			newDieuKhoanBaoCao.NamHoc = _namHoc;
			newDieuKhoanBaoCao.HocKy = _hocKy;
			newDieuKhoanBaoCao.GhiChu = _ghiChu;
			newDieuKhoanBaoCao.TrangThai = _trangThai;
			return newDieuKhoanBaoCao;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Id is required")]




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ParentId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? ParentId
		{
			get
			{
				return this.entityData.ParentId; 
			}
			
			set
			{
				if (this.entityData.ParentId == value)
					return;
				
                OnPropertyChanging("ParentId");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.ParentId, this.entityData.ParentId);
				this.entityData.ParentId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.ParentId, this.entityData.ParentId);
				OnPropertyChanged("ParentId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PhanLoai property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 250)]
		public virtual System.String PhanLoai
		{
			get
			{
				return this.entityData.PhanLoai; 
			}
			
			set
			{
				if (this.entityData.PhanLoai == value)
					return;
				
                OnPropertyChanging("PhanLoai");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.PhanLoai, this.entityData.PhanLoai);
				this.entityData.PhanLoai = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.PhanLoai, this.entityData.PhanLoai);
				OnPropertyChanged("PhanLoai");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IdChucNang property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? IdChucNang
		{
			get
			{
				return this.entityData.IdChucNang; 
			}
			
			set
			{
				if (this.entityData.IdChucNang == value)
					return;
				
                OnPropertyChanging("IdChucNang");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.IdChucNang, this.entityData.IdChucNang);
				this.entityData.IdChucNang = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.IdChucNang, this.entityData.IdChucNang);
				OnPropertyChanged("IdChucNang");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NoiDung property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String NoiDung
		{
			get
			{
				return this.entityData.NoiDung; 
			}
			
			set
			{
				if (this.entityData.NoiDung == value)
					return;
				
                OnPropertyChanging("NoiDung");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.NoiDung, this.entityData.NoiDung);
				this.entityData.NoiDung = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.NoiDung, this.entityData.NoiDung);
				OnPropertyChanged("NoiDung");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ThuTu property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? ThuTu
		{
			get
			{
				return this.entityData.ThuTu; 
			}
			
			set
			{
				if (this.entityData.ThuTu == value)
					return;
				
                OnPropertyChanging("ThuTu");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.ThuTu, this.entityData.ThuTu);
				this.entityData.ThuTu = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.ThuTu, this.entityData.ThuTu);
				OnPropertyChanged("ThuTu");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NgayCapNhat property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String NgayCapNhat
		{
			get
			{
				return this.entityData.NgayCapNhat; 
			}
			
			set
			{
				if (this.entityData.NgayCapNhat == value)
					return;
				
                OnPropertyChanging("NgayCapNhat");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.NgayCapNhat, this.entityData.NgayCapNhat);
				this.entityData.NgayCapNhat = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.NgayCapNhat, this.entityData.NgayCapNhat);
				OnPropertyChanged("NgayCapNhat");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NguoiCapNhat property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 250)]
		public virtual System.String NguoiCapNhat
		{
			get
			{
				return this.entityData.NguoiCapNhat; 
			}
			
			set
			{
				if (this.entityData.NguoiCapNhat == value)
					return;
				
                OnPropertyChanging("NguoiCapNhat");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.NguoiCapNhat, this.entityData.NguoiCapNhat);
				this.entityData.NguoiCapNhat = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.NguoiCapNhat, this.entityData.NguoiCapNhat);
				OnPropertyChanged("NguoiCapNhat");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NamHoc property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String NamHoc
		{
			get
			{
				return this.entityData.NamHoc; 
			}
			
			set
			{
				if (this.entityData.NamHoc == value)
					return;
				
                OnPropertyChanging("NamHoc");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.NamHoc, this.entityData.NamHoc);
				this.entityData.NamHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.NamHoc, this.entityData.NamHoc);
				OnPropertyChanged("NamHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the HocKy property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String HocKy
		{
			get
			{
				return this.entityData.HocKy; 
			}
			
			set
			{
				if (this.entityData.HocKy == value)
					return;
				
                OnPropertyChanging("HocKy");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.HocKy, this.entityData.HocKy);
				this.entityData.HocKy = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.HocKy, this.entityData.HocKy);
				OnPropertyChanged("HocKy");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the GhiChu property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String GhiChu
		{
			get
			{
				return this.entityData.GhiChu; 
			}
			
			set
			{
				if (this.entityData.GhiChu == value)
					return;
				
                OnPropertyChanging("GhiChu");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.GhiChu, this.entityData.GhiChu);
				this.entityData.GhiChu = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.GhiChu, this.entityData.GhiChu);
				OnPropertyChanged("GhiChu");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TrangThai property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? TrangThai
		{
			get
			{
				return this.entityData.TrangThai; 
			}
			
			set
			{
				if (this.entityData.TrangThai == value)
					return;
				
                OnPropertyChanging("TrangThai");                    
				OnColumnChanging(DieuKhoanBaoCaoColumn.TrangThai, this.entityData.TrangThai);
				this.entityData.TrangThai = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieuKhoanBaoCaoColumn.TrangThai, this.entityData.TrangThai);
				OnPropertyChanged("TrangThai");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("PhanLoai", "Phan Loai", 250));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("NgayCapNhat", "Ngay Cap Nhat", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("NguoiCapNhat", "Nguoi Cap Nhat", 250));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("NamHoc", "Nam Hoc", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("HocKy", "Hoc Ky", 20));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "DieuKhoanBaoCao"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID", "ParentID", "PhanLoai", "IDChucNang", "NoiDung", "ThuTu", "NgayCapNhat", "NguoiCapNhat", "NamHoc", "HocKy", "GhiChu", "TrangThai"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as DieuKhoanBaoCaoEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (DieuKhoanBaoCao) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<DieuKhoanBaoCao>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as DieuKhoanBaoCao);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed DieuKhoanBaoCao Entity 
		///</summary>
		protected virtual DieuKhoanBaoCao Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			DieuKhoanBaoCao copy = new DieuKhoanBaoCao();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.ParentId = this.ParentId;
				copy.PhanLoai = this.PhanLoai;
				copy.IdChucNang = this.IdChucNang;
				copy.NoiDung = this.NoiDung;
				copy.ThuTu = this.ThuTu;
				copy.NgayCapNhat = this.NgayCapNhat;
				copy.NguoiCapNhat = this.NguoiCapNhat;
				copy.NamHoc = this.NamHoc;
				copy.HocKy = this.HocKy;
				copy.GhiChu = this.GhiChu;
				copy.TrangThai = this.TrangThai;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed DieuKhoanBaoCao Entity 
		///</summary>
		public virtual DieuKhoanBaoCao Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed DieuKhoanBaoCao Entity which is a deep copy of the current entity.
		///</summary>
		public virtual DieuKhoanBaoCao DeepCopy()
		{
			return EntityHelper.Clone<DieuKhoanBaoCao>(this as DieuKhoanBaoCao);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as DieuKhoanBaoCaoEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new DieuKhoanBaoCaoEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as DieuKhoanBaoCaoEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(DieuKhoanBaoCaoColumn column)
		{
			switch(column)
			{
					case DieuKhoanBaoCaoColumn.Id:
					return entityData.Id != _originalData.Id;
					case DieuKhoanBaoCaoColumn.ParentId:
					return entityData.ParentId != _originalData.ParentId;
					case DieuKhoanBaoCaoColumn.PhanLoai:
					return entityData.PhanLoai != _originalData.PhanLoai;
					case DieuKhoanBaoCaoColumn.IdChucNang:
					return entityData.IdChucNang != _originalData.IdChucNang;
					case DieuKhoanBaoCaoColumn.NoiDung:
					return entityData.NoiDung != _originalData.NoiDung;
					case DieuKhoanBaoCaoColumn.ThuTu:
					return entityData.ThuTu != _originalData.ThuTu;
					case DieuKhoanBaoCaoColumn.NgayCapNhat:
					return entityData.NgayCapNhat != _originalData.NgayCapNhat;
					case DieuKhoanBaoCaoColumn.NguoiCapNhat:
					return entityData.NguoiCapNhat != _originalData.NguoiCapNhat;
					case DieuKhoanBaoCaoColumn.NamHoc:
					return entityData.NamHoc != _originalData.NamHoc;
					case DieuKhoanBaoCaoColumn.HocKy:
					return entityData.HocKy != _originalData.HocKy;
					case DieuKhoanBaoCaoColumn.GhiChu:
					return entityData.GhiChu != _originalData.GhiChu;
					case DieuKhoanBaoCaoColumn.TrangThai:
					return entityData.TrangThai != _originalData.TrangThai;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< DieuKhoanBaoCaoColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.ParentId != _originalData.ParentId;
			result = result || entityData.PhanLoai != _originalData.PhanLoai;
			result = result || entityData.IdChucNang != _originalData.IdChucNang;
			result = result || entityData.NoiDung != _originalData.NoiDung;
			result = result || entityData.ThuTu != _originalData.ThuTu;
			result = result || entityData.NgayCapNhat != _originalData.NgayCapNhat;
			result = result || entityData.NguoiCapNhat != _originalData.NguoiCapNhat;
			result = result || entityData.NamHoc != _originalData.NamHoc;
			result = result || entityData.HocKy != _originalData.HocKy;
			result = result || entityData.GhiChu != _originalData.GhiChu;
			result = result || entityData.TrangThai != _originalData.TrangThai;
			return result;
		}	
		
		///<summary>
		///  Returns a DieuKhoanBaoCao Entity with the original data.
		///</summary>
		public DieuKhoanBaoCao GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateDieuKhoanBaoCao(
				_originalData.ParentId,
				_originalData.PhanLoai,
				_originalData.IdChucNang,
				_originalData.NoiDung,
				_originalData.ThuTu,
				_originalData.NgayCapNhat,
				_originalData.NguoiCapNhat,
				_originalData.NamHoc,
				_originalData.HocKy,
				_originalData.GhiChu,
				_originalData.TrangThai
				);
				
			return (DieuKhoanBaoCao)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="DieuKhoanBaoCaoBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is DieuKhoanBaoCaoBase)
				return ValueEquals(this, (DieuKhoanBaoCaoBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="DieuKhoanBaoCaoBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.ParentId == null) ? string.Empty : this.ParentId.ToString()).GetHashCode() ^ 
					((this.PhanLoai == null) ? string.Empty : this.PhanLoai.ToString()).GetHashCode() ^ 
					((this.IdChucNang == null) ? string.Empty : this.IdChucNang.ToString()).GetHashCode() ^ 
					((this.NoiDung == null) ? string.Empty : this.NoiDung.ToString()).GetHashCode() ^ 
					((this.ThuTu == null) ? string.Empty : this.ThuTu.ToString()).GetHashCode() ^ 
					((this.NgayCapNhat == null) ? string.Empty : this.NgayCapNhat.ToString()).GetHashCode() ^ 
					((this.NguoiCapNhat == null) ? string.Empty : this.NguoiCapNhat.ToString()).GetHashCode() ^ 
					((this.NamHoc == null) ? string.Empty : this.NamHoc.ToString()).GetHashCode() ^ 
					((this.HocKy == null) ? string.Empty : this.HocKy.ToString()).GetHashCode() ^ 
					((this.GhiChu == null) ? string.Empty : this.GhiChu.ToString()).GetHashCode() ^ 
					((this.TrangThai == null) ? string.Empty : this.TrangThai.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="DieuKhoanBaoCaoBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(DieuKhoanBaoCaoBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="DieuKhoanBaoCaoBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="DieuKhoanBaoCaoBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="DieuKhoanBaoCaoBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(DieuKhoanBaoCaoBase Object1, DieuKhoanBaoCaoBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.ParentId != null && Object2.ParentId != null )
			{
				if (Object1.ParentId != Object2.ParentId)
					equal = false;
			}
			else if (Object1.ParentId == null ^ Object2.ParentId == null )
			{
				equal = false;
			}
			if ( Object1.PhanLoai != null && Object2.PhanLoai != null )
			{
				if (Object1.PhanLoai != Object2.PhanLoai)
					equal = false;
			}
			else if (Object1.PhanLoai == null ^ Object2.PhanLoai == null )
			{
				equal = false;
			}
			if ( Object1.IdChucNang != null && Object2.IdChucNang != null )
			{
				if (Object1.IdChucNang != Object2.IdChucNang)
					equal = false;
			}
			else if (Object1.IdChucNang == null ^ Object2.IdChucNang == null )
			{
				equal = false;
			}
			if ( Object1.NoiDung != null && Object2.NoiDung != null )
			{
				if (Object1.NoiDung != Object2.NoiDung)
					equal = false;
			}
			else if (Object1.NoiDung == null ^ Object2.NoiDung == null )
			{
				equal = false;
			}
			if ( Object1.ThuTu != null && Object2.ThuTu != null )
			{
				if (Object1.ThuTu != Object2.ThuTu)
					equal = false;
			}
			else if (Object1.ThuTu == null ^ Object2.ThuTu == null )
			{
				equal = false;
			}
			if ( Object1.NgayCapNhat != null && Object2.NgayCapNhat != null )
			{
				if (Object1.NgayCapNhat != Object2.NgayCapNhat)
					equal = false;
			}
			else if (Object1.NgayCapNhat == null ^ Object2.NgayCapNhat == null )
			{
				equal = false;
			}
			if ( Object1.NguoiCapNhat != null && Object2.NguoiCapNhat != null )
			{
				if (Object1.NguoiCapNhat != Object2.NguoiCapNhat)
					equal = false;
			}
			else if (Object1.NguoiCapNhat == null ^ Object2.NguoiCapNhat == null )
			{
				equal = false;
			}
			if ( Object1.NamHoc != null && Object2.NamHoc != null )
			{
				if (Object1.NamHoc != Object2.NamHoc)
					equal = false;
			}
			else if (Object1.NamHoc == null ^ Object2.NamHoc == null )
			{
				equal = false;
			}
			if ( Object1.HocKy != null && Object2.HocKy != null )
			{
				if (Object1.HocKy != Object2.HocKy)
					equal = false;
			}
			else if (Object1.HocKy == null ^ Object2.HocKy == null )
			{
				equal = false;
			}
			if ( Object1.GhiChu != null && Object2.GhiChu != null )
			{
				if (Object1.GhiChu != Object2.GhiChu)
					equal = false;
			}
			else if (Object1.GhiChu == null ^ Object2.GhiChu == null )
			{
				equal = false;
			}
			if ( Object1.TrangThai != null && Object2.TrangThai != null )
			{
				if (Object1.TrangThai != Object2.TrangThai)
					equal = false;
			}
			else if (Object1.TrangThai == null ^ Object2.TrangThai == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((DieuKhoanBaoCaoBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static DieuKhoanBaoCaoComparer GetComparer()
        {
            return new DieuKhoanBaoCaoComparer();
        }
        */

        // Comparer delegates back to DieuKhoanBaoCao
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(DieuKhoanBaoCao rhs, DieuKhoanBaoCaoColumn which)
        {
            switch (which)
            {
            	
            	
            	case DieuKhoanBaoCaoColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case DieuKhoanBaoCaoColumn.ParentId:
            		return this.ParentId.Value.CompareTo(rhs.ParentId.Value);
            		
            		                 
            	
            	
            	case DieuKhoanBaoCaoColumn.PhanLoai:
            		return this.PhanLoai.CompareTo(rhs.PhanLoai);
            		
            		                 
            	
            	
            	case DieuKhoanBaoCaoColumn.IdChucNang:
            		return this.IdChucNang.Value.CompareTo(rhs.IdChucNang.Value);
            		
            		                 
            	
            	
            	case DieuKhoanBaoCaoColumn.NoiDung:
            		return this.NoiDung.CompareTo(rhs.NoiDung);
            		
            		                 
            	
            	
            	case DieuKhoanBaoCaoColumn.ThuTu:
            		return this.ThuTu.Value.CompareTo(rhs.ThuTu.Value);
            		
            		                 
            	
            	
            	case DieuKhoanBaoCaoColumn.NgayCapNhat:
            		return this.NgayCapNhat.CompareTo(rhs.NgayCapNhat);
            		
            		                 
            	
            	
            	case DieuKhoanBaoCaoColumn.NguoiCapNhat:
            		return this.NguoiCapNhat.CompareTo(rhs.NguoiCapNhat);
            		
            		                 
            	
            	
            	case DieuKhoanBaoCaoColumn.NamHoc:
            		return this.NamHoc.CompareTo(rhs.NamHoc);
            		
            		                 
            	
            	
            	case DieuKhoanBaoCaoColumn.HocKy:
            		return this.HocKy.CompareTo(rhs.HocKy);
            		
            		                 
            	
            	
            	case DieuKhoanBaoCaoColumn.GhiChu:
            		return this.GhiChu.CompareTo(rhs.GhiChu);
            		
            		                 
            	
            	
            	case DieuKhoanBaoCaoColumn.TrangThai:
            		return this.TrangThai.Value.CompareTo(rhs.TrangThai.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<DieuKhoanBaoCaoKey> Members
		
		// member variable for the EntityId property
		private DieuKhoanBaoCaoKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual DieuKhoanBaoCaoKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new DieuKhoanBaoCaoKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) ]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("DieuKhoanBaoCao")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{13}{12}- Id: {0}{12}- ParentId: {1}{12}- PhanLoai: {2}{12}- IdChucNang: {3}{12}- NoiDung: {4}{12}- ThuTu: {5}{12}- NgayCapNhat: {6}{12}- NguoiCapNhat: {7}{12}- NamHoc: {8}{12}- HocKy: {9}{12}- GhiChu: {10}{12}- TrangThai: {11}{12}{14}", 
				this.Id,
				(this.ParentId == null) ? string.Empty : this.ParentId.ToString(),
				(this.PhanLoai == null) ? string.Empty : this.PhanLoai.ToString(),
				(this.IdChucNang == null) ? string.Empty : this.IdChucNang.ToString(),
				(this.NoiDung == null) ? string.Empty : this.NoiDung.ToString(),
				(this.ThuTu == null) ? string.Empty : this.ThuTu.ToString(),
				(this.NgayCapNhat == null) ? string.Empty : this.NgayCapNhat.ToString(),
				(this.NguoiCapNhat == null) ? string.Empty : this.NguoiCapNhat.ToString(),
				(this.NamHoc == null) ? string.Empty : this.NamHoc.ToString(),
				(this.HocKy == null) ? string.Empty : this.HocKy.ToString(),
				(this.GhiChu == null) ? string.Empty : this.GhiChu.ToString(),
				(this.TrangThai == null) ? string.Empty : this.TrangThai.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'DieuKhoanBaoCao' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class DieuKhoanBaoCaoEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "DieuKhoanBaoCao"</remarks>
		public System.Int32 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// ParentID : 
		/// </summary>
		public System.Int32? ParentId = null;
		
		/// <summary>
		/// PhanLoai : 
		/// </summary>
		public System.String PhanLoai = null;
		
		/// <summary>
		/// IDChucNang : 
		/// </summary>
		public System.Int32? IdChucNang = null;
		
		/// <summary>
		/// NoiDung : 
		/// </summary>
		public System.String NoiDung = null;
		
		/// <summary>
		/// ThuTu : 
		/// </summary>
		public System.Int32? ThuTu = null;
		
		/// <summary>
		/// NgayCapNhat : 
		/// </summary>
		public System.String NgayCapNhat = null;
		
		/// <summary>
		/// NguoiCapNhat : 
		/// </summary>
		public System.String NguoiCapNhat = null;
		
		/// <summary>
		/// NamHoc : 
		/// </summary>
		public System.String NamHoc = null;
		
		/// <summary>
		/// HocKy : 
		/// </summary>
		public System.String HocKy = null;
		
		/// <summary>
		/// GhiChu : 
		/// </summary>
		public System.String GhiChu = null;
		
		/// <summary>
		/// TrangThai : 
		/// </summary>
		public System.Boolean? TrangThai = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			DieuKhoanBaoCaoEntityData _tmp = new DieuKhoanBaoCaoEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.ParentId = this.ParentId;
			_tmp.PhanLoai = this.PhanLoai;
			_tmp.IdChucNang = this.IdChucNang;
			_tmp.NoiDung = this.NoiDung;
			_tmp.ThuTu = this.ThuTu;
			_tmp.NgayCapNhat = this.NgayCapNhat;
			_tmp.NguoiCapNhat = this.NguoiCapNhat;
			_tmp.NamHoc = this.NamHoc;
			_tmp.HocKy = this.HocKy;
			_tmp.GhiChu = this.GhiChu;
			_tmp.TrangThai = this.TrangThai;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			DieuKhoanBaoCaoEntityData _tmp = new DieuKhoanBaoCaoEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.ParentId = this.ParentId;
			_tmp.PhanLoai = this.PhanLoai;
			_tmp.IdChucNang = this.IdChucNang;
			_tmp.NoiDung = this.NoiDung;
			_tmp.ThuTu = this.ThuTu;
			_tmp.NgayCapNhat = this.NgayCapNhat;
			_tmp.NguoiCapNhat = this.NguoiCapNhat;
			_tmp.NamHoc = this.NamHoc;
			_tmp.HocKy = this.HocKy;
			_tmp.GhiChu = this.GhiChu;
			_tmp.TrangThai = this.TrangThai;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false)]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DieuKhoanBaoCaoColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(DieuKhoanBaoCaoColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DieuKhoanBaoCaoColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(DieuKhoanBaoCaoColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DieuKhoanBaoCaoColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(DieuKhoanBaoCaoColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				DieuKhoanBaoCaoEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new DieuKhoanBaoCaoEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DieuKhoanBaoCaoColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(DieuKhoanBaoCaoColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				DieuKhoanBaoCaoEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new DieuKhoanBaoCaoEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region DieuKhoanBaoCaoEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="DieuKhoanBaoCao"/> object.
	/// </remarks>
	public class DieuKhoanBaoCaoEventArgs : System.EventArgs
	{
		private DieuKhoanBaoCaoColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the DieuKhoanBaoCaoEventArgs class.
		///</summary>
		public DieuKhoanBaoCaoEventArgs(DieuKhoanBaoCaoColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the DieuKhoanBaoCaoEventArgs class.
		///</summary>
		public DieuKhoanBaoCaoEventArgs(DieuKhoanBaoCaoColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The DieuKhoanBaoCaoColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="DieuKhoanBaoCaoColumn" />
		public DieuKhoanBaoCaoColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all DieuKhoanBaoCao related events.
	///</summary>
	public delegate void DieuKhoanBaoCaoEventHandler(object sender, DieuKhoanBaoCaoEventArgs e);
	
	#region DieuKhoanBaoCaoComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class DieuKhoanBaoCaoComparer : System.Collections.Generic.IComparer<DieuKhoanBaoCao>
	{
		DieuKhoanBaoCaoColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:DieuKhoanBaoCaoComparer"/> class.
        /// </summary>
		public DieuKhoanBaoCaoComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:DieuKhoanBaoCaoComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public DieuKhoanBaoCaoComparer(DieuKhoanBaoCaoColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="DieuKhoanBaoCao"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="DieuKhoanBaoCao"/> to compare.</param>
        /// <param name="b">The second <c>DieuKhoanBaoCao</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(DieuKhoanBaoCao a, DieuKhoanBaoCao b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(DieuKhoanBaoCao entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(DieuKhoanBaoCao a, DieuKhoanBaoCao b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public DieuKhoanBaoCaoColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region DieuKhoanBaoCaoKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="DieuKhoanBaoCao"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class DieuKhoanBaoCaoKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the DieuKhoanBaoCaoKey class.
		/// </summary>
		public DieuKhoanBaoCaoKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the DieuKhoanBaoCaoKey class.
		/// </summary>
		public DieuKhoanBaoCaoKey(DieuKhoanBaoCaoBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the DieuKhoanBaoCaoKey class.
		/// </summary>
		public DieuKhoanBaoCaoKey(System.Int32 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private DieuKhoanBaoCaoBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public DieuKhoanBaoCaoBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int32 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int32 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Id"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region DieuKhoanBaoCaoColumn Enum
	
	/// <summary>
	/// Enumerate the DieuKhoanBaoCao columns.
	/// </summary>
	[Serializable]
	public enum DieuKhoanBaoCaoColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		Id = 1,
		/// <summary>
		/// ParentId : 
		/// </summary>
		[EnumTextValue("Parent Id")]
		[ColumnEnum("ParentID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		ParentId = 2,
		/// <summary>
		/// PhanLoai : 
		/// </summary>
		[EnumTextValue("Phan Loai")]
		[ColumnEnum("PhanLoai", typeof(System.String), System.Data.DbType.String, false, false, true, 250)]
		PhanLoai = 3,
		/// <summary>
		/// IdChucNang : 
		/// </summary>
		[EnumTextValue("Id Chuc Nang")]
		[ColumnEnum("IDChucNang", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		IdChucNang = 4,
		/// <summary>
		/// NoiDung : 
		/// </summary>
		[EnumTextValue("Noi Dung")]
		[ColumnEnum("NoiDung", typeof(System.String), System.Data.DbType.String, false, false, true)]
		NoiDung = 5,
		/// <summary>
		/// ThuTu : 
		/// </summary>
		[EnumTextValue("Thu Tu")]
		[ColumnEnum("ThuTu", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		ThuTu = 6,
		/// <summary>
		/// NgayCapNhat : 
		/// </summary>
		[EnumTextValue("Ngay Cap Nhat")]
		[ColumnEnum("NgayCapNhat", typeof(System.String), System.Data.DbType.String, false, false, true, 20)]
		NgayCapNhat = 7,
		/// <summary>
		/// NguoiCapNhat : 
		/// </summary>
		[EnumTextValue("Nguoi Cap Nhat")]
		[ColumnEnum("NguoiCapNhat", typeof(System.String), System.Data.DbType.String, false, false, true, 250)]
		NguoiCapNhat = 8,
		/// <summary>
		/// NamHoc : 
		/// </summary>
		[EnumTextValue("Nam Hoc")]
		[ColumnEnum("NamHoc", typeof(System.String), System.Data.DbType.String, false, false, true, 20)]
		NamHoc = 9,
		/// <summary>
		/// HocKy : 
		/// </summary>
		[EnumTextValue("Hoc Ky")]
		[ColumnEnum("HocKy", typeof(System.String), System.Data.DbType.String, false, false, true, 20)]
		HocKy = 10,
		/// <summary>
		/// GhiChu : 
		/// </summary>
		[EnumTextValue("Ghi Chu")]
		[ColumnEnum("GhiChu", typeof(System.String), System.Data.DbType.String, false, false, true)]
		GhiChu = 11,
		/// <summary>
		/// TrangThai : 
		/// </summary>
		[EnumTextValue("Trang Thai")]
		[ColumnEnum("TrangThai", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		TrangThai = 12
	}//End enum

	#endregion DieuKhoanBaoCaoColumn Enum

} // end namespace
