
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file PhanNhomMonHocTinhDinhMuc.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using PMS.Entities.Validation;
#endregion

namespace PMS.Entities
{
	///<summary>
	/// An object representation of the 'PhanNhomMonHocTinhDinhMuc' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class PhanNhomMonHocTinhDinhMucBase : EntityBase, IPhanNhomMonHocTinhDinhMuc, IEntityId<PhanNhomMonHocTinhDinhMucKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private PhanNhomMonHocTinhDinhMucEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private PhanNhomMonHocTinhDinhMucEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private PhanNhomMonHocTinhDinhMucEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<PhanNhomMonHocTinhDinhMuc> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PhanNhomMonHocTinhDinhMucEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PhanNhomMonHocTinhDinhMucEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="PhanNhomMonHocTinhDinhMucBase"/> instance.
		///</summary>
		public PhanNhomMonHocTinhDinhMucBase()
		{
			this.entityData = new PhanNhomMonHocTinhDinhMucEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="PhanNhomMonHocTinhDinhMucBase"/> instance.
		///</summary>
		///<param name="_maMonHoc"></param>
		///<param name="_maNhomMon"></param>
		///<param name="_namHoc"></param>
		///<param name="_hocKy"></param>
		public PhanNhomMonHocTinhDinhMucBase(System.String _maMonHoc, System.String _maNhomMon, 
			System.String _namHoc, System.String _hocKy)
		{
			this.entityData = new PhanNhomMonHocTinhDinhMucEntityData();
			this.backupData = null;

			this.MaMonHoc = _maMonHoc;
			this.MaNhomMon = _maNhomMon;
			this.NamHoc = _namHoc;
			this.HocKy = _hocKy;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="PhanNhomMonHocTinhDinhMuc"/> instance.
		///</summary>
		///<param name="_maMonHoc"></param>
		///<param name="_maNhomMon"></param>
		///<param name="_namHoc"></param>
		///<param name="_hocKy"></param>
		public static PhanNhomMonHocTinhDinhMuc CreatePhanNhomMonHocTinhDinhMuc(System.String _maMonHoc, System.String _maNhomMon, 
			System.String _namHoc, System.String _hocKy)
		{
			PhanNhomMonHocTinhDinhMuc newPhanNhomMonHocTinhDinhMuc = new PhanNhomMonHocTinhDinhMuc();
			newPhanNhomMonHocTinhDinhMuc.MaMonHoc = _maMonHoc;
			newPhanNhomMonHocTinhDinhMuc.MaNhomMon = _maNhomMon;
			newPhanNhomMonHocTinhDinhMuc.NamHoc = _namHoc;
			newPhanNhomMonHocTinhDinhMuc.HocKy = _hocKy;
			return newPhanNhomMonHocTinhDinhMuc;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Id is required")]




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(PhanNhomMonHocTinhDinhMucColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PhanNhomMonHocTinhDinhMucColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaMonHoc property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String MaMonHoc
		{
			get
			{
				return this.entityData.MaMonHoc; 
			}
			
			set
			{
				if (this.entityData.MaMonHoc == value)
					return;
				
                OnPropertyChanging("MaMonHoc");                    
				OnColumnChanging(PhanNhomMonHocTinhDinhMucColumn.MaMonHoc, this.entityData.MaMonHoc);
				this.entityData.MaMonHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PhanNhomMonHocTinhDinhMucColumn.MaMonHoc, this.entityData.MaMonHoc);
				OnPropertyChanged("MaMonHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaNhomMon property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String MaNhomMon
		{
			get
			{
				return this.entityData.MaNhomMon; 
			}
			
			set
			{
				if (this.entityData.MaNhomMon == value)
					return;
				
                OnPropertyChanging("MaNhomMon");                    
				OnColumnChanging(PhanNhomMonHocTinhDinhMucColumn.MaNhomMon, this.entityData.MaNhomMon);
				this.entityData.MaNhomMon = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PhanNhomMonHocTinhDinhMucColumn.MaNhomMon, this.entityData.MaNhomMon);
				OnPropertyChanged("MaNhomMon");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NamHoc property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String NamHoc
		{
			get
			{
				return this.entityData.NamHoc; 
			}
			
			set
			{
				if (this.entityData.NamHoc == value)
					return;
				
                OnPropertyChanging("NamHoc");                    
				OnColumnChanging(PhanNhomMonHocTinhDinhMucColumn.NamHoc, this.entityData.NamHoc);
				this.entityData.NamHoc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PhanNhomMonHocTinhDinhMucColumn.NamHoc, this.entityData.NamHoc);
				OnPropertyChanged("NamHoc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the HocKy property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String HocKy
		{
			get
			{
				return this.entityData.HocKy; 
			}
			
			set
			{
				if (this.entityData.HocKy == value)
					return;
				
                OnPropertyChanging("HocKy");                    
				OnColumnChanging(PhanNhomMonHocTinhDinhMucColumn.HocKy, this.entityData.HocKy);
				this.entityData.HocKy = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PhanNhomMonHocTinhDinhMucColumn.HocKy, this.entityData.HocKy);
				OnPropertyChanged("HocKy");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("MaMonHoc", "Ma Mon Hoc", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("MaNhomMon", "Ma Nhom Mon", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("NamHoc", "Nam Hoc", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("HocKy", "Hoc Ky", 20));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "PhanNhomMonHocTinhDinhMuc"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Id", "MaMonHoc", "MaNhomMon", "NamHoc", "HocKy"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as PhanNhomMonHocTinhDinhMucEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (PhanNhomMonHocTinhDinhMuc) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<PhanNhomMonHocTinhDinhMuc>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as PhanNhomMonHocTinhDinhMuc);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed PhanNhomMonHocTinhDinhMuc Entity 
		///</summary>
		protected virtual PhanNhomMonHocTinhDinhMuc Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			PhanNhomMonHocTinhDinhMuc copy = new PhanNhomMonHocTinhDinhMuc();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.MaMonHoc = this.MaMonHoc;
				copy.MaNhomMon = this.MaNhomMon;
				copy.NamHoc = this.NamHoc;
				copy.HocKy = this.HocKy;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed PhanNhomMonHocTinhDinhMuc Entity 
		///</summary>
		public virtual PhanNhomMonHocTinhDinhMuc Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed PhanNhomMonHocTinhDinhMuc Entity which is a deep copy of the current entity.
		///</summary>
		public virtual PhanNhomMonHocTinhDinhMuc DeepCopy()
		{
			return EntityHelper.Clone<PhanNhomMonHocTinhDinhMuc>(this as PhanNhomMonHocTinhDinhMuc);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as PhanNhomMonHocTinhDinhMucEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new PhanNhomMonHocTinhDinhMucEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as PhanNhomMonHocTinhDinhMucEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(PhanNhomMonHocTinhDinhMucColumn column)
		{
			switch(column)
			{
					case PhanNhomMonHocTinhDinhMucColumn.Id:
					return entityData.Id != _originalData.Id;
					case PhanNhomMonHocTinhDinhMucColumn.MaMonHoc:
					return entityData.MaMonHoc != _originalData.MaMonHoc;
					case PhanNhomMonHocTinhDinhMucColumn.MaNhomMon:
					return entityData.MaNhomMon != _originalData.MaNhomMon;
					case PhanNhomMonHocTinhDinhMucColumn.NamHoc:
					return entityData.NamHoc != _originalData.NamHoc;
					case PhanNhomMonHocTinhDinhMucColumn.HocKy:
					return entityData.HocKy != _originalData.HocKy;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< PhanNhomMonHocTinhDinhMucColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.MaMonHoc != _originalData.MaMonHoc;
			result = result || entityData.MaNhomMon != _originalData.MaNhomMon;
			result = result || entityData.NamHoc != _originalData.NamHoc;
			result = result || entityData.HocKy != _originalData.HocKy;
			return result;
		}	
		
		///<summary>
		///  Returns a PhanNhomMonHocTinhDinhMuc Entity with the original data.
		///</summary>
		public PhanNhomMonHocTinhDinhMuc GetOriginalEntity()
		{
			if (_originalData != null)
				return CreatePhanNhomMonHocTinhDinhMuc(
				_originalData.MaMonHoc,
				_originalData.MaNhomMon,
				_originalData.NamHoc,
				_originalData.HocKy
				);
				
			return (PhanNhomMonHocTinhDinhMuc)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="PhanNhomMonHocTinhDinhMucBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is PhanNhomMonHocTinhDinhMucBase)
				return ValueEquals(this, (PhanNhomMonHocTinhDinhMucBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="PhanNhomMonHocTinhDinhMucBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.MaMonHoc == null) ? string.Empty : this.MaMonHoc.ToString()).GetHashCode() ^ 
					((this.MaNhomMon == null) ? string.Empty : this.MaNhomMon.ToString()).GetHashCode() ^ 
					((this.NamHoc == null) ? string.Empty : this.NamHoc.ToString()).GetHashCode() ^ 
					((this.HocKy == null) ? string.Empty : this.HocKy.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="PhanNhomMonHocTinhDinhMucBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(PhanNhomMonHocTinhDinhMucBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="PhanNhomMonHocTinhDinhMucBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="PhanNhomMonHocTinhDinhMucBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="PhanNhomMonHocTinhDinhMucBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(PhanNhomMonHocTinhDinhMucBase Object1, PhanNhomMonHocTinhDinhMucBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.MaMonHoc != null && Object2.MaMonHoc != null )
			{
				if (Object1.MaMonHoc != Object2.MaMonHoc)
					equal = false;
			}
			else if (Object1.MaMonHoc == null ^ Object2.MaMonHoc == null )
			{
				equal = false;
			}
			if ( Object1.MaNhomMon != null && Object2.MaNhomMon != null )
			{
				if (Object1.MaNhomMon != Object2.MaNhomMon)
					equal = false;
			}
			else if (Object1.MaNhomMon == null ^ Object2.MaNhomMon == null )
			{
				equal = false;
			}
			if ( Object1.NamHoc != null && Object2.NamHoc != null )
			{
				if (Object1.NamHoc != Object2.NamHoc)
					equal = false;
			}
			else if (Object1.NamHoc == null ^ Object2.NamHoc == null )
			{
				equal = false;
			}
			if ( Object1.HocKy != null && Object2.HocKy != null )
			{
				if (Object1.HocKy != Object2.HocKy)
					equal = false;
			}
			else if (Object1.HocKy == null ^ Object2.HocKy == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((PhanNhomMonHocTinhDinhMucBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static PhanNhomMonHocTinhDinhMucComparer GetComparer()
        {
            return new PhanNhomMonHocTinhDinhMucComparer();
        }
        */

        // Comparer delegates back to PhanNhomMonHocTinhDinhMuc
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(PhanNhomMonHocTinhDinhMuc rhs, PhanNhomMonHocTinhDinhMucColumn which)
        {
            switch (which)
            {
            	
            	
            	case PhanNhomMonHocTinhDinhMucColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case PhanNhomMonHocTinhDinhMucColumn.MaMonHoc:
            		return this.MaMonHoc.CompareTo(rhs.MaMonHoc);
            		
            		                 
            	
            	
            	case PhanNhomMonHocTinhDinhMucColumn.MaNhomMon:
            		return this.MaNhomMon.CompareTo(rhs.MaNhomMon);
            		
            		                 
            	
            	
            	case PhanNhomMonHocTinhDinhMucColumn.NamHoc:
            		return this.NamHoc.CompareTo(rhs.NamHoc);
            		
            		                 
            	
            	
            	case PhanNhomMonHocTinhDinhMucColumn.HocKy:
            		return this.HocKy.CompareTo(rhs.HocKy);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<PhanNhomMonHocTinhDinhMucKey> Members
		
		// member variable for the EntityId property
		private PhanNhomMonHocTinhDinhMucKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual PhanNhomMonHocTinhDinhMucKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new PhanNhomMonHocTinhDinhMucKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) ]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("PhanNhomMonHocTinhDinhMuc")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- Id: {0}{5}- MaMonHoc: {1}{5}- MaNhomMon: {2}{5}- NamHoc: {3}{5}- HocKy: {4}{5}{7}", 
				this.Id,
				(this.MaMonHoc == null) ? string.Empty : this.MaMonHoc.ToString(),
				(this.MaNhomMon == null) ? string.Empty : this.MaNhomMon.ToString(),
				(this.NamHoc == null) ? string.Empty : this.NamHoc.ToString(),
				(this.HocKy == null) ? string.Empty : this.HocKy.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'PhanNhomMonHocTinhDinhMuc' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class PhanNhomMonHocTinhDinhMucEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "PhanNhomMonHocTinhDinhMuc"</remarks>
		public System.Int32 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// MaMonHoc : 
		/// </summary>
		public System.String MaMonHoc = null;
		
		/// <summary>
		/// MaNhomMon : 
		/// </summary>
		public System.String MaNhomMon = null;
		
		/// <summary>
		/// NamHoc : 
		/// </summary>
		public System.String NamHoc = null;
		
		/// <summary>
		/// HocKy : 
		/// </summary>
		public System.String HocKy = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			PhanNhomMonHocTinhDinhMucEntityData _tmp = new PhanNhomMonHocTinhDinhMucEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.MaMonHoc = this.MaMonHoc;
			_tmp.MaNhomMon = this.MaNhomMon;
			_tmp.NamHoc = this.NamHoc;
			_tmp.HocKy = this.HocKy;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			PhanNhomMonHocTinhDinhMucEntityData _tmp = new PhanNhomMonHocTinhDinhMucEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.MaMonHoc = this.MaMonHoc;
			_tmp.MaNhomMon = this.MaNhomMon;
			_tmp.NamHoc = this.NamHoc;
			_tmp.HocKy = this.HocKy;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false)]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PhanNhomMonHocTinhDinhMucColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(PhanNhomMonHocTinhDinhMucColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PhanNhomMonHocTinhDinhMucColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(PhanNhomMonHocTinhDinhMucColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PhanNhomMonHocTinhDinhMucColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(PhanNhomMonHocTinhDinhMucColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				PhanNhomMonHocTinhDinhMucEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new PhanNhomMonHocTinhDinhMucEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PhanNhomMonHocTinhDinhMucColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(PhanNhomMonHocTinhDinhMucColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				PhanNhomMonHocTinhDinhMucEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new PhanNhomMonHocTinhDinhMucEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region PhanNhomMonHocTinhDinhMucEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="PhanNhomMonHocTinhDinhMuc"/> object.
	/// </remarks>
	public class PhanNhomMonHocTinhDinhMucEventArgs : System.EventArgs
	{
		private PhanNhomMonHocTinhDinhMucColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the PhanNhomMonHocTinhDinhMucEventArgs class.
		///</summary>
		public PhanNhomMonHocTinhDinhMucEventArgs(PhanNhomMonHocTinhDinhMucColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the PhanNhomMonHocTinhDinhMucEventArgs class.
		///</summary>
		public PhanNhomMonHocTinhDinhMucEventArgs(PhanNhomMonHocTinhDinhMucColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The PhanNhomMonHocTinhDinhMucColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="PhanNhomMonHocTinhDinhMucColumn" />
		public PhanNhomMonHocTinhDinhMucColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all PhanNhomMonHocTinhDinhMuc related events.
	///</summary>
	public delegate void PhanNhomMonHocTinhDinhMucEventHandler(object sender, PhanNhomMonHocTinhDinhMucEventArgs e);
	
	#region PhanNhomMonHocTinhDinhMucComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class PhanNhomMonHocTinhDinhMucComparer : System.Collections.Generic.IComparer<PhanNhomMonHocTinhDinhMuc>
	{
		PhanNhomMonHocTinhDinhMucColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:PhanNhomMonHocTinhDinhMucComparer"/> class.
        /// </summary>
		public PhanNhomMonHocTinhDinhMucComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PhanNhomMonHocTinhDinhMucComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public PhanNhomMonHocTinhDinhMucComparer(PhanNhomMonHocTinhDinhMucColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="PhanNhomMonHocTinhDinhMuc"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="PhanNhomMonHocTinhDinhMuc"/> to compare.</param>
        /// <param name="b">The second <c>PhanNhomMonHocTinhDinhMuc</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(PhanNhomMonHocTinhDinhMuc a, PhanNhomMonHocTinhDinhMuc b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(PhanNhomMonHocTinhDinhMuc entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(PhanNhomMonHocTinhDinhMuc a, PhanNhomMonHocTinhDinhMuc b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public PhanNhomMonHocTinhDinhMucColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region PhanNhomMonHocTinhDinhMucKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="PhanNhomMonHocTinhDinhMuc"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class PhanNhomMonHocTinhDinhMucKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the PhanNhomMonHocTinhDinhMucKey class.
		/// </summary>
		public PhanNhomMonHocTinhDinhMucKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the PhanNhomMonHocTinhDinhMucKey class.
		/// </summary>
		public PhanNhomMonHocTinhDinhMucKey(PhanNhomMonHocTinhDinhMucBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the PhanNhomMonHocTinhDinhMucKey class.
		/// </summary>
		public PhanNhomMonHocTinhDinhMucKey(System.Int32 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private PhanNhomMonHocTinhDinhMucBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public PhanNhomMonHocTinhDinhMucBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int32 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int32 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Id"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region PhanNhomMonHocTinhDinhMucColumn Enum
	
	/// <summary>
	/// Enumerate the PhanNhomMonHocTinhDinhMuc columns.
	/// </summary>
	[Serializable]
	public enum PhanNhomMonHocTinhDinhMucColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("Id", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		Id = 1,
		/// <summary>
		/// MaMonHoc : 
		/// </summary>
		[EnumTextValue("Ma Mon Hoc")]
		[ColumnEnum("MaMonHoc", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		MaMonHoc = 2,
		/// <summary>
		/// MaNhomMon : 
		/// </summary>
		[EnumTextValue("Ma Nhom Mon")]
		[ColumnEnum("MaNhomMon", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		MaNhomMon = 3,
		/// <summary>
		/// NamHoc : 
		/// </summary>
		[EnumTextValue("Nam Hoc")]
		[ColumnEnum("NamHoc", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		NamHoc = 4,
		/// <summary>
		/// HocKy : 
		/// </summary>
		[EnumTextValue("Hoc Ky")]
		[ColumnEnum("HocKy", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 20)]
		HocKy = 5
	}//End enum

	#endregion PhanNhomMonHocTinhDinhMucColumn Enum

} // end namespace
