
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file TaiKhoanDuocPhep.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using PMS.Entities.Validation;
#endregion

namespace PMS.Entities
{
	///<summary>
	/// An object representation of the 'TaiKhoanDuocPhep' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class TaiKhoanDuocPhepBase : EntityBase, ITaiKhoanDuocPhep, IEntityId<TaiKhoanDuocPhepKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private TaiKhoanDuocPhepEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private TaiKhoanDuocPhepEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private TaiKhoanDuocPhepEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<TaiKhoanDuocPhep> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event TaiKhoanDuocPhepEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event TaiKhoanDuocPhepEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="TaiKhoanDuocPhepBase"/> instance.
		///</summary>
		public TaiKhoanDuocPhepBase()
		{
			this.entityData = new TaiKhoanDuocPhepEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="TaiKhoanDuocPhepBase"/> instance.
		///</summary>
		///<param name="_idTaiKhoan"></param>
		///<param name="_idThanhPhan"></param>
		public TaiKhoanDuocPhepBase(System.Int32 _idTaiKhoan, System.String _idThanhPhan)
		{
			this.entityData = new TaiKhoanDuocPhepEntityData();
			this.backupData = null;

			this.IdTaiKhoan = _idTaiKhoan;
			this.IdThanhPhan = _idThanhPhan;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="TaiKhoanDuocPhep"/> instance.
		///</summary>
		///<param name="_idTaiKhoan"></param>
		///<param name="_idThanhPhan"></param>
		public static TaiKhoanDuocPhep CreateTaiKhoanDuocPhep(System.Int32 _idTaiKhoan, System.String _idThanhPhan)
		{
			TaiKhoanDuocPhep newTaiKhoanDuocPhep = new TaiKhoanDuocPhep();
			newTaiKhoanDuocPhep.IdTaiKhoan = _idTaiKhoan;
			newTaiKhoanDuocPhep.IdThanhPhan = _idThanhPhan;
			return newTaiKhoanDuocPhep;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the IdTaiKhoan property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "IdTaiKhoan is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int32 IdTaiKhoan
		{
			get
			{
				return this.entityData.IdTaiKhoan; 
			}
			
			set
			{
				if (this.entityData.IdTaiKhoan == value)
					return;
				
                OnPropertyChanging("IdTaiKhoan");                    
				OnColumnChanging(TaiKhoanDuocPhepColumn.IdTaiKhoan, this.entityData.IdTaiKhoan);
				this.entityData.IdTaiKhoan = value;
				this.EntityId.IdTaiKhoan = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TaiKhoanDuocPhepColumn.IdTaiKhoan, this.entityData.IdTaiKhoan);
				OnPropertyChanged("IdTaiKhoan");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the IdTaiKhoan property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the IdTaiKhoan property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalIdTaiKhoan
		{
			get { return this.entityData.OriginalIdTaiKhoan; }
			set { this.entityData.OriginalIdTaiKhoan = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the IdThanhPhan property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[XmlElement(IsNullable=true)]
		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 250)]
		public virtual System.String IdThanhPhan
		{
			get
			{
				return this.entityData.IdThanhPhan; 
			}
			
			set
			{
				if (this.entityData.IdThanhPhan == value)
					return;
				
                OnPropertyChanging("IdThanhPhan");                    
				OnColumnChanging(TaiKhoanDuocPhepColumn.IdThanhPhan, this.entityData.IdThanhPhan);
				this.entityData.IdThanhPhan = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TaiKhoanDuocPhepColumn.IdThanhPhan, this.entityData.IdThanhPhan);
				OnPropertyChanged("IdThanhPhan");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("IdThanhPhan", "Id Thanh Phan", 250));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "TaiKhoanDuocPhep"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"IdTaiKhoan", "IdThanhPhan"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as TaiKhoanDuocPhepEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (TaiKhoanDuocPhep) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<TaiKhoanDuocPhep>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as TaiKhoanDuocPhep);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed TaiKhoanDuocPhep Entity 
		///</summary>
		protected virtual TaiKhoanDuocPhep Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			TaiKhoanDuocPhep copy = new TaiKhoanDuocPhep();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.IdTaiKhoan = this.IdTaiKhoan;
					copy.OriginalIdTaiKhoan = this.OriginalIdTaiKhoan;
				copy.IdThanhPhan = this.IdThanhPhan;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed TaiKhoanDuocPhep Entity 
		///</summary>
		public virtual TaiKhoanDuocPhep Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed TaiKhoanDuocPhep Entity which is a deep copy of the current entity.
		///</summary>
		public virtual TaiKhoanDuocPhep DeepCopy()
		{
			return EntityHelper.Clone<TaiKhoanDuocPhep>(this as TaiKhoanDuocPhep);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as TaiKhoanDuocPhepEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new TaiKhoanDuocPhepEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as TaiKhoanDuocPhepEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(TaiKhoanDuocPhepColumn column)
		{
			switch(column)
			{
					case TaiKhoanDuocPhepColumn.IdTaiKhoan:
					return entityData.IdTaiKhoan != _originalData.IdTaiKhoan;
					case TaiKhoanDuocPhepColumn.IdThanhPhan:
					return entityData.IdThanhPhan != _originalData.IdThanhPhan;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< TaiKhoanDuocPhepColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.IdTaiKhoan != _originalData.IdTaiKhoan;
			result = result || entityData.IdThanhPhan != _originalData.IdThanhPhan;
			return result;
		}	
		
		///<summary>
		///  Returns a TaiKhoanDuocPhep Entity with the original data.
		///</summary>
		public TaiKhoanDuocPhep GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateTaiKhoanDuocPhep(
				_originalData.IdTaiKhoan,
				_originalData.IdThanhPhan
				);
				
			return (TaiKhoanDuocPhep)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="TaiKhoanDuocPhepBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is TaiKhoanDuocPhepBase)
				return ValueEquals(this, (TaiKhoanDuocPhepBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="TaiKhoanDuocPhepBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.IdTaiKhoan.GetHashCode() ^ 
					((this.IdThanhPhan == null) ? string.Empty : this.IdThanhPhan.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="TaiKhoanDuocPhepBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(TaiKhoanDuocPhepBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="TaiKhoanDuocPhepBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="TaiKhoanDuocPhepBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="TaiKhoanDuocPhepBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(TaiKhoanDuocPhepBase Object1, TaiKhoanDuocPhepBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.IdTaiKhoan != Object2.IdTaiKhoan)
				equal = false;
			if ( Object1.IdThanhPhan != null && Object2.IdThanhPhan != null )
			{
				if (Object1.IdThanhPhan != Object2.IdThanhPhan)
					equal = false;
			}
			else if (Object1.IdThanhPhan == null ^ Object2.IdThanhPhan == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((TaiKhoanDuocPhepBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static TaiKhoanDuocPhepComparer GetComparer()
        {
            return new TaiKhoanDuocPhepComparer();
        }
        */

        // Comparer delegates back to TaiKhoanDuocPhep
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(TaiKhoanDuocPhep rhs, TaiKhoanDuocPhepColumn which)
        {
            switch (which)
            {
            	
            	
            	case TaiKhoanDuocPhepColumn.IdTaiKhoan:
            		return this.IdTaiKhoan.CompareTo(rhs.IdTaiKhoan);
            		
            		                 
            	
            	
            	case TaiKhoanDuocPhepColumn.IdThanhPhan:
            		return this.IdThanhPhan.CompareTo(rhs.IdThanhPhan);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<TaiKhoanDuocPhepKey> Members
		
		// member variable for the EntityId property
		private TaiKhoanDuocPhepKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual TaiKhoanDuocPhepKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new TaiKhoanDuocPhepKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) ]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("TaiKhoanDuocPhep")
					.Append("|").Append( this.IdTaiKhoan.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{3}{2}- IdTaiKhoan: {0}{2}- IdThanhPhan: {1}{2}{4}", 
				this.IdTaiKhoan,
				(this.IdThanhPhan == null) ? string.Empty : this.IdThanhPhan.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'TaiKhoanDuocPhep' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class TaiKhoanDuocPhepEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// IdTaiKhoan : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "TaiKhoanDuocPhep"</remarks>
		public System.Int32 IdTaiKhoan;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Int32 OriginalIdTaiKhoan;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// IdThanhPhan : 
		/// </summary>
		public System.String IdThanhPhan = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			TaiKhoanDuocPhepEntityData _tmp = new TaiKhoanDuocPhepEntityData();
						
			_tmp.IdTaiKhoan = this.IdTaiKhoan;
			_tmp.OriginalIdTaiKhoan = this.OriginalIdTaiKhoan;
			
			_tmp.IdThanhPhan = this.IdThanhPhan;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			TaiKhoanDuocPhepEntityData _tmp = new TaiKhoanDuocPhepEntityData();
						
			_tmp.IdTaiKhoan = this.IdTaiKhoan;
			_tmp.OriginalIdTaiKhoan = this.OriginalIdTaiKhoan;
			
			_tmp.IdThanhPhan = this.IdThanhPhan;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false)]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TaiKhoanDuocPhepColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(TaiKhoanDuocPhepColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TaiKhoanDuocPhepColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(TaiKhoanDuocPhepColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TaiKhoanDuocPhepColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(TaiKhoanDuocPhepColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				TaiKhoanDuocPhepEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new TaiKhoanDuocPhepEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TaiKhoanDuocPhepColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(TaiKhoanDuocPhepColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				TaiKhoanDuocPhepEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new TaiKhoanDuocPhepEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region TaiKhoanDuocPhepEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="TaiKhoanDuocPhep"/> object.
	/// </remarks>
	public class TaiKhoanDuocPhepEventArgs : System.EventArgs
	{
		private TaiKhoanDuocPhepColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the TaiKhoanDuocPhepEventArgs class.
		///</summary>
		public TaiKhoanDuocPhepEventArgs(TaiKhoanDuocPhepColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the TaiKhoanDuocPhepEventArgs class.
		///</summary>
		public TaiKhoanDuocPhepEventArgs(TaiKhoanDuocPhepColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The TaiKhoanDuocPhepColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="TaiKhoanDuocPhepColumn" />
		public TaiKhoanDuocPhepColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all TaiKhoanDuocPhep related events.
	///</summary>
	public delegate void TaiKhoanDuocPhepEventHandler(object sender, TaiKhoanDuocPhepEventArgs e);
	
	#region TaiKhoanDuocPhepComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class TaiKhoanDuocPhepComparer : System.Collections.Generic.IComparer<TaiKhoanDuocPhep>
	{
		TaiKhoanDuocPhepColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:TaiKhoanDuocPhepComparer"/> class.
        /// </summary>
		public TaiKhoanDuocPhepComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:TaiKhoanDuocPhepComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public TaiKhoanDuocPhepComparer(TaiKhoanDuocPhepColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="TaiKhoanDuocPhep"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="TaiKhoanDuocPhep"/> to compare.</param>
        /// <param name="b">The second <c>TaiKhoanDuocPhep</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(TaiKhoanDuocPhep a, TaiKhoanDuocPhep b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(TaiKhoanDuocPhep entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(TaiKhoanDuocPhep a, TaiKhoanDuocPhep b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public TaiKhoanDuocPhepColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region TaiKhoanDuocPhepKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="TaiKhoanDuocPhep"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class TaiKhoanDuocPhepKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the TaiKhoanDuocPhepKey class.
		/// </summary>
		public TaiKhoanDuocPhepKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the TaiKhoanDuocPhepKey class.
		/// </summary>
		public TaiKhoanDuocPhepKey(TaiKhoanDuocPhepBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.IdTaiKhoan = entity.IdTaiKhoan;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the TaiKhoanDuocPhepKey class.
		/// </summary>
		public TaiKhoanDuocPhepKey(System.Int32 _idTaiKhoan)
		{
			#region Init Properties

			this.IdTaiKhoan = _idTaiKhoan;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private TaiKhoanDuocPhepBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public TaiKhoanDuocPhepBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the IdTaiKhoan property
		private System.Int32 _idTaiKhoan;
		
		/// <summary>
		/// Gets or sets the IdTaiKhoan property.
		/// </summary>
		public System.Int32 IdTaiKhoan
		{
			get { return _idTaiKhoan; }
			set
			{
				if ( this.Entity != null )
					this.Entity.IdTaiKhoan = value;
				
				_idTaiKhoan = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				IdTaiKhoan = ( values["IdTaiKhoan"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["IdTaiKhoan"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("IdTaiKhoan", IdTaiKhoan);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("IdTaiKhoan: {0}{1}",
								IdTaiKhoan,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region TaiKhoanDuocPhepColumn Enum
	
	/// <summary>
	/// Enumerate the TaiKhoanDuocPhep columns.
	/// </summary>
	[Serializable]
	public enum TaiKhoanDuocPhepColumn : int
	{
		/// <summary>
		/// IdTaiKhoan : 
		/// </summary>
		[EnumTextValue("Id Tai Khoan")]
		[ColumnEnum("IdTaiKhoan", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
		IdTaiKhoan = 1,
		/// <summary>
		/// IdThanhPhan : 
		/// </summary>
		[EnumTextValue("Id Thanh Phan")]
		[ColumnEnum("IdThanhPhan", typeof(System.String), System.Data.DbType.String, false, false, true, 250)]
		IdThanhPhan = 2
	}//End enum

	#endregion TaiKhoanDuocPhepColumn Enum

} // end namespace
