using System;
using System.ComponentModel;

namespace PMS.Entities
{
	/// <summary>
	///		The data structure representation of the 'psc_CoSo' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IPscCoSo 
	{
		/// <summary>			
		/// CampusID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "psc_CoSo"</remarks>
		System.String CampusId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalCampusId { get; set; }
			
		
		
		/// <summary>
		/// CampusName : 
		/// </summary>
		System.String  CampusName  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


