/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file ViewBoMon.cs instead.
*/
#region Using Directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Runtime.Serialization;
using System.Xml.Serialization;
#endregion

namespace PMS.Entities
{
	///<summary>
	/// An object representation of the 'View_BoMon' view. [No description found in the database]	
	///</summary>
	[Serializable]
	[CLSCompliant(true)]
	[ToolboxItem("ViewBoMonBase")]
	public abstract partial class ViewBoMonBase : System.IComparable, System.ICloneable, INotifyPropertyChanged
	{
		
		#region Variable Declarations
		
		/// <summary>
		/// MaBoMon : 
		/// </summary>
		private System.String		  _maBoMon = string.Empty;
		
		/// <summary>
		/// TenBoMon : 
		/// </summary>
		private System.String		  _tenBoMon = string.Empty;
		
		/// <summary>
		/// Object that contains data to associate with this object
		/// </summary>
		private object _tag;
		
		/// <summary>
		/// Suppresses Entity Events from Firing, 
		/// useful when loading the entities from the database.
		/// </summary>
	    [NonSerialized] 
		private bool suppressEntityEvents = false;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="ViewBoMonBase"/> instance.
		///</summary>
		public ViewBoMonBase()
		{
		}		
		
		///<summary>
		/// Creates a new <see cref="ViewBoMonBase"/> instance.
		///</summary>
		///<param name="_maBoMon"></param>
		///<param name="_tenBoMon"></param>
		public ViewBoMonBase(System.String _maBoMon, System.String _tenBoMon)
		{
			this._maBoMon = _maBoMon;
			this._tenBoMon = _tenBoMon;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="ViewBoMon"/> instance.
		///</summary>
		///<param name="_maBoMon"></param>
		///<param name="_tenBoMon"></param>
		public static ViewBoMon CreateViewBoMon(System.String _maBoMon, System.String _tenBoMon)
		{
			ViewBoMon newViewBoMon = new ViewBoMon();
			newViewBoMon.MaBoMon = _maBoMon;
			newViewBoMon.TenBoMon = _tenBoMon;
			return newViewBoMon;
		}
				
		#endregion Constructors
		
		#region Properties	
		/// <summary>
		/// 	Gets or Sets the MaBoMon property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String MaBoMon
		{
			get
			{
				return this._maBoMon; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "MaBoMon does not allow null values.");
				if (_maBoMon == value)
					return;
					
				this._maBoMon = value;
				this._isDirty = true;
				
				OnPropertyChanged("MaBoMon");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the TenBoMon property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String TenBoMon
		{
			get
			{
				return this._tenBoMon; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "TenBoMon does not allow null values.");
				if (_tenBoMon == value)
					return;
					
				this._tenBoMon = value;
				this._isDirty = true;
				
				OnPropertyChanged("TenBoMon");
			}
		}
		
		
		/// <summary>
		///     Gets or sets the object that contains supplemental data about this object.
		/// </summary>
		/// <value>Object</value>
		[System.ComponentModel.Bindable(false)]
		[LocalizableAttribute(false)]
		[DescriptionAttribute("Object containing data to be associated with this object")]
		public virtual object Tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if (this._tag == value)
					return;
		
				this._tag = value;
			}
		}
	
		/// <summary>
		/// Determines whether this entity is to suppress events while set to true.
		/// </summary>
		[System.ComponentModel.Bindable(false)]
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public bool SuppressEntityEvents
		{	
			get
			{
				return suppressEntityEvents;
			}
			set
			{
				suppressEntityEvents = value;
			}	
		}

		private bool _isDeleted = false;
		/// <summary>
		/// Gets a value indicating if object has been <see cref="MarkToDelete"/>. ReadOnly.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDeleted
		{
			get { return this._isDeleted; }
		}


		private bool _isDirty = false;
		/// <summary>
		///	Gets a value indicating  if the object has been modified from its original state.
		/// </summary>
		///<value>True if object has been modified from its original state; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDirty
		{
			get { return this._isDirty; }
		}
		

		private bool _isNew = true;
		/// <summary>
		///	Gets a value indicating if the object is new.
		/// </summary>
		///<value>True if objectis new; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsNew
		{
			get { return this._isNew; }
			set { this._isNew = value; }
		}

		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public string ViewName
		{
			get { return "View_BoMon"; }
		}

		
		#endregion
		
		#region Methods	
		
		/// <summary>
		/// Accepts the changes made to this object by setting each flags to false.
		/// </summary>
		public virtual void AcceptChanges()
		{
			this._isDeleted = false;
			this._isDirty = false;
			this._isNew = false;
			OnPropertyChanged(string.Empty);
		}
		
		
		///<summary>
		///  Revert all changes and restore original values.
		///  Currently not supported.
		///</summary>
		/// <exception cref="NotSupportedException">This method is not currently supported and always throws this exception.</exception>
		public virtual void CancelChanges()
		{
			throw new NotSupportedException("Method currently not Supported.");
		}
		
		///<summary>
		///   Marks entity to be deleted.
		///</summary>
		public virtual void MarkToDelete()
		{
			this._isDeleted = true;
		}
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed ViewBoMonBase Entity 
		///</summary>
		public virtual ViewBoMonBase Copy()
		{
			//shallow copy entity
			ViewBoMon copy = new ViewBoMon();
				copy.MaBoMon = this.MaBoMon;
				copy.TenBoMon = this.TenBoMon;
			copy.AcceptChanges();
			return (ViewBoMon)copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Deep Copy of this entity.
		///</summary>
		public object Clone(){
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		#endregion
		
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="ViewBoMonBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(ViewBoMonBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="ViewBoMonBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="ViewBoMonBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="ViewBoMonBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(ViewBoMonBase Object1, ViewBoMonBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;

			bool equal = true;
			if (Object1.MaBoMon != Object2.MaBoMon)
				equal = false;
			if (Object1.TenBoMon != Object2.TenBoMon)
				equal = false;
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
		}
	
		#endregion
		
		#region INotifyPropertyChanged Members
		
		/// <summary>
      /// Event to indicate that a property has changed.
      /// </summary>
		[field:NonSerialized]
		public event PropertyChangedEventHandler PropertyChanged;

		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="propertyName">The name of the property that has changed.</param>
		protected virtual void OnPropertyChanged(string propertyName)
		{ 
			OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
		}
		
		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="e">PropertyChangedEventArgs</param>
		protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
		{
			if (!SuppressEntityEvents)
			{
				if (null != PropertyChanged)
				{
					PropertyChanged(this, e);
				}
			}
		}
		
		#endregion
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="entity">The entity.</param>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public static object GetPropertyValueByName(ViewBoMon entity, string propertyName)
		{
			switch (propertyName)
			{
				case "MaBoMon":
					return entity.MaBoMon;
				case "TenBoMon":
					return entity.TenBoMon;
			}
			return null;
		}
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public object GetPropertyValueByName(string propertyName)
		{			
			return GetPropertyValueByName(this as ViewBoMon, propertyName);
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{3}{2}- MaBoMon: {0}{2}- TenBoMon: {1}{2}", 
				this.MaBoMon,
				this.TenBoMon,
				System.Environment.NewLine, 
				this.GetType());
		}
	
	}//End Class
	
	
	/// <summary>
	/// Enumerate the ViewBoMon columns.
	/// </summary>
	[Serializable]
	public enum ViewBoMonColumn
	{
		/// <summary>
		/// MaBoMon : 
		/// </summary>
		[EnumTextValue("MaBoMon")]
		[ColumnEnum("MaBoMon", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 20)]
		MaBoMon,
		/// <summary>
		/// TenBoMon : 
		/// </summary>
		[EnumTextValue("TenBoMon")]
		[ColumnEnum("TenBoMon", typeof(System.String), System.Data.DbType.String, false, false, false, 255)]
		TenBoMon
	}//End enum

} // end namespace
