
/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file CongThucTinhQuyDoiTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using PMS.Entities;
using PMS.Data;
using PMS.Data.Bases;

#endregion

namespace PMS.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="CongThucTinhQuyDoi"/> objects (entity, collection and repository).
    /// </summary>
   public partial class CongThucTinhQuyDoiTest
    {
    	// the CongThucTinhQuyDoi instance used to test the repository.
		protected CongThucTinhQuyDoi mock;
		
		// the TList<CongThucTinhQuyDoi> instance used to test the repository.
		protected TList<CongThucTinhQuyDoi> mockCollection;
		
		protected static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the CongThucTinhQuyDoi Entity with the {0} --", PMS.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock CongThucTinhQuyDoi entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.CongThucTinhQuyDoiProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.CongThucTinhQuyDoiProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all CongThucTinhQuyDoi objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.CongThucTinhQuyDoiProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.CongThucTinhQuyDoiProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.CongThucTinhQuyDoiProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all CongThucTinhQuyDoi children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.CongThucTinhQuyDoiProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.CongThucTinhQuyDoiProvider.DeepLoading += new EntityProviderBaseCore<CongThucTinhQuyDoi, CongThucTinhQuyDoiKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.CongThucTinhQuyDoiProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("CongThucTinhQuyDoi instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.CongThucTinhQuyDoiProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock CongThucTinhQuyDoi entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				CongThucTinhQuyDoi mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.CongThucTinhQuyDoiProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.CongThucTinhQuyDoiProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.CongThucTinhQuyDoiProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock CongThucTinhQuyDoi entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (CongThucTinhQuyDoi)CreateMockInstance(tm);
				DataRepository.CongThucTinhQuyDoiProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.CongThucTinhQuyDoiProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.CongThucTinhQuyDoiProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock CongThucTinhQuyDoi entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_CongThucTinhQuyDoi.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock CongThucTinhQuyDoi entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_CongThucTinhQuyDoi.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<CongThucTinhQuyDoi>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a CongThucTinhQuyDoi collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_CongThucTinhQuyDoiCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<CongThucTinhQuyDoi> mockCollection = new TList<CongThucTinhQuyDoi>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<CongThucTinhQuyDoi> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a CongThucTinhQuyDoi collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_CongThucTinhQuyDoiCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<CongThucTinhQuyDoi>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<CongThucTinhQuyDoi> mockCollection = (TList<CongThucTinhQuyDoi>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<CongThucTinhQuyDoi> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				CongThucTinhQuyDoi entity = CreateMockInstance(tm);
				bool result = DataRepository.CongThucTinhQuyDoiProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
				TList<CongThucTinhQuyDoi> t0 = DataRepository.CongThucTinhQuyDoiProvider.GetByMaLoaiCongThuc(tm, entity.MaLoaiCongThuc, 0, 10);
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				CongThucTinhQuyDoi entity = CreateMockInstance(tm);
				bool result = DataRepository.CongThucTinhQuyDoiProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				CongThucTinhQuyDoi t0 = DataRepository.CongThucTinhQuyDoiProvider.GetByMaCongThuc(tm, entity.MaCongThuc);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				CongThucTinhQuyDoi entity = mock.Copy() as CongThucTinhQuyDoi;
				entity = (CongThucTinhQuyDoi)mock.Clone();
				Assert.IsTrue(CongThucTinhQuyDoi.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				CongThucTinhQuyDoi mock = CreateMockInstance(tm);
				bool result = DataRepository.CongThucTinhQuyDoiProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				CongThucTinhQuyDoiQuery query = new CongThucTinhQuyDoiQuery();
			
				query.AppendEquals(CongThucTinhQuyDoiColumn.MaCongThuc, mock.MaCongThuc.ToString());
				if(mock.MaLoaiCongThuc != null)
					query.AppendEquals(CongThucTinhQuyDoiColumn.MaLoaiCongThuc, mock.MaLoaiCongThuc.ToString());
				if(mock.NamHoc != null)
					query.AppendEquals(CongThucTinhQuyDoiColumn.NamHoc, mock.NamHoc.ToString());
				if(mock.HocKy != null)
					query.AppendEquals(CongThucTinhQuyDoiColumn.HocKy, mock.HocKy.ToString());
				query.AppendEquals(CongThucTinhQuyDoiColumn.CongThuc, mock.CongThuc.ToString());
				query.AppendEquals(CongThucTinhQuyDoiColumn.ToanHangSuDung, mock.ToanHangSuDung.ToString());
				if(mock.ApDung != null)
					query.AppendEquals(CongThucTinhQuyDoiColumn.ApDung, mock.ApDung.ToString());
				if(mock.DienGiai != null)
					query.AppendEquals(CongThucTinhQuyDoiColumn.DienGiai, mock.DienGiai.ToString());
				if(mock.TinhVuotDinhMuc != null)
					query.AppendEquals(CongThucTinhQuyDoiColumn.TinhVuotDinhMuc, mock.TinhVuotDinhMuc.ToString());
				if(mock.TinhVuotTran != null)
					query.AppendEquals(CongThucTinhQuyDoiColumn.TinhVuotTran, mock.TinhVuotTran.ToString());
				
				TList<CongThucTinhQuyDoi> results = DataRepository.CongThucTinhQuyDoiProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed CongThucTinhQuyDoi Entity with mock values.
		///</summary>
		static public CongThucTinhQuyDoi CreateMockInstance_Generated(TransactionManager tm)
		{		
			CongThucTinhQuyDoi mock = new CongThucTinhQuyDoi();
						
			mock.NamHoc = TestUtility.Instance.RandomString(9, false);;
			mock.HocKy = TestUtility.Instance.RandomString(9, false);;
			mock.CongThuc = TestUtility.Instance.RandomString(2, false);;
			mock.ToanHangSuDung = TestUtility.Instance.RandomString(2, false);;
			mock.ApDung = TestUtility.Instance.RandomBoolean();
			mock.DienGiai = TestUtility.Instance.RandomString(2, false);;
			mock.TinhVuotDinhMuc = TestUtility.Instance.RandomBoolean();
			mock.TinhVuotTran = TestUtility.Instance.RandomBoolean();
			
			//OneToOneRelationship
			LoaiCongThuc mockLoaiCongThucByMaLoaiCongThuc = LoaiCongThucTest.CreateMockInstance(tm);
			DataRepository.LoaiCongThucProvider.Insert(tm, mockLoaiCongThucByMaLoaiCongThuc);
			mock.MaLoaiCongThuc = mockLoaiCongThucByMaLoaiCongThuc.MaLoaiCongThuc;
		
			// create a temporary collection and add the item to it
			TList<CongThucTinhQuyDoi> tempMockCollection = new TList<CongThucTinhQuyDoi>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (CongThucTinhQuyDoi)mock;
		}
		
		
		///<summary>
		///  Update the Typed CongThucTinhQuyDoi Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, CongThucTinhQuyDoi mock)
		{
			mock.NamHoc = TestUtility.Instance.RandomString(9, false);;
			mock.HocKy = TestUtility.Instance.RandomString(9, false);;
			mock.CongThuc = TestUtility.Instance.RandomString(2, false);;
			mock.ToanHangSuDung = TestUtility.Instance.RandomString(2, false);;
			mock.ApDung = TestUtility.Instance.RandomBoolean();
			mock.DienGiai = TestUtility.Instance.RandomString(2, false);;
			mock.TinhVuotDinhMuc = TestUtility.Instance.RandomBoolean();
			mock.TinhVuotTran = TestUtility.Instance.RandomBoolean();
			
			//OneToOneRelationship
			LoaiCongThuc mockLoaiCongThucByMaLoaiCongThuc = LoaiCongThucTest.CreateMockInstance(tm);
			DataRepository.LoaiCongThucProvider.Insert(tm, mockLoaiCongThucByMaLoaiCongThuc);
			mock.MaLoaiCongThuc = mockLoaiCongThucByMaLoaiCongThuc.MaLoaiCongThuc;
					
		}
		#endregion
    }
}
