
/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file LopHocPhanTheoNhomGiangVienTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using PMS.Entities;
using PMS.Data;
using PMS.Data.Bases;

#endregion

namespace PMS.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="LopHocPhanTheoNhomGiangVien"/> objects (entity, collection and repository).
    /// </summary>
   public partial class LopHocPhanTheoNhomGiangVienTest
    {
    	// the LopHocPhanTheoNhomGiangVien instance used to test the repository.
		protected LopHocPhanTheoNhomGiangVien mock;
		
		// the TList<LopHocPhanTheoNhomGiangVien> instance used to test the repository.
		protected TList<LopHocPhanTheoNhomGiangVien> mockCollection;
		
		protected static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the LopHocPhanTheoNhomGiangVien Entity with the {0} --", PMS.Data.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock LopHocPhanTheoNhomGiangVien entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.LopHocPhanTheoNhomGiangVienProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.LopHocPhanTheoNhomGiangVienProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all LopHocPhanTheoNhomGiangVien objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.LopHocPhanTheoNhomGiangVienProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.LopHocPhanTheoNhomGiangVienProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.LopHocPhanTheoNhomGiangVienProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all LopHocPhanTheoNhomGiangVien children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.LopHocPhanTheoNhomGiangVienProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.LopHocPhanTheoNhomGiangVienProvider.DeepLoading += new EntityProviderBaseCore<LopHocPhanTheoNhomGiangVien, LopHocPhanTheoNhomGiangVienKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.LopHocPhanTheoNhomGiangVienProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("LopHocPhanTheoNhomGiangVien instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.LopHocPhanTheoNhomGiangVienProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock LopHocPhanTheoNhomGiangVien entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				LopHocPhanTheoNhomGiangVien mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.LopHocPhanTheoNhomGiangVienProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.LopHocPhanTheoNhomGiangVienProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.LopHocPhanTheoNhomGiangVienProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock LopHocPhanTheoNhomGiangVien entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (LopHocPhanTheoNhomGiangVien)CreateMockInstance(tm);
				DataRepository.LopHocPhanTheoNhomGiangVienProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.LopHocPhanTheoNhomGiangVienProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.LopHocPhanTheoNhomGiangVienProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock LopHocPhanTheoNhomGiangVien entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_LopHocPhanTheoNhomGiangVien.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock LopHocPhanTheoNhomGiangVien entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_LopHocPhanTheoNhomGiangVien.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<LopHocPhanTheoNhomGiangVien>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a LopHocPhanTheoNhomGiangVien collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_LopHocPhanTheoNhomGiangVienCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<LopHocPhanTheoNhomGiangVien> mockCollection = new TList<LopHocPhanTheoNhomGiangVien>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<LopHocPhanTheoNhomGiangVien> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a LopHocPhanTheoNhomGiangVien collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_LopHocPhanTheoNhomGiangVienCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<LopHocPhanTheoNhomGiangVien>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<LopHocPhanTheoNhomGiangVien> mockCollection = (TList<LopHocPhanTheoNhomGiangVien>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<LopHocPhanTheoNhomGiangVien> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				LopHocPhanTheoNhomGiangVien entity = CreateMockInstance(tm);
				bool result = DataRepository.LopHocPhanTheoNhomGiangVienProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				LopHocPhanTheoNhomGiangVien entity = CreateMockInstance(tm);
				bool result = DataRepository.LopHocPhanTheoNhomGiangVienProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				LopHocPhanTheoNhomGiangVien t0 = DataRepository.LopHocPhanTheoNhomGiangVienProvider.GetByMaLopHocPhanMaNhomGiangVien(tm, entity.MaLopHocPhan, entity.MaNhomGiangVien);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				LopHocPhanTheoNhomGiangVien entity = mock.Copy() as LopHocPhanTheoNhomGiangVien;
				entity = (LopHocPhanTheoNhomGiangVien)mock.Clone();
				Assert.IsTrue(LopHocPhanTheoNhomGiangVien.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				LopHocPhanTheoNhomGiangVien mock = CreateMockInstance(tm);
				bool result = DataRepository.LopHocPhanTheoNhomGiangVienProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				LopHocPhanTheoNhomGiangVienQuery query = new LopHocPhanTheoNhomGiangVienQuery();
			
				query.AppendEquals(LopHocPhanTheoNhomGiangVienColumn.MaLopHocPhan, mock.MaLopHocPhan.ToString());
				query.AppendEquals(LopHocPhanTheoNhomGiangVienColumn.MaNhomGiangVien, mock.MaNhomGiangVien.ToString());
				
				TList<LopHocPhanTheoNhomGiangVien> results = DataRepository.LopHocPhanTheoNhomGiangVienProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed LopHocPhanTheoNhomGiangVien Entity with mock values.
		///</summary>
		static public LopHocPhanTheoNhomGiangVien CreateMockInstance_Generated(TransactionManager tm)
		{		
			LopHocPhanTheoNhomGiangVien mock = new LopHocPhanTheoNhomGiangVien();
						
			mock.MaLopHocPhan = TestUtility.Instance.RandomString(24, false);;
			mock.MaNhomGiangVien = TestUtility.Instance.RandomString(24, false);;
			
		
			// create a temporary collection and add the item to it
			TList<LopHocPhanTheoNhomGiangVien> tempMockCollection = new TList<LopHocPhanTheoNhomGiangVien>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (LopHocPhanTheoNhomGiangVien)mock;
		}
		
		
		///<summary>
		///  Update the Typed LopHocPhanTheoNhomGiangVien Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, LopHocPhanTheoNhomGiangVien mock)
		{
			
		}
		#endregion
    }
}
